
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ContactSettings` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model ContactSettings
 * 
 */
export type ContactSettingsModel = runtime.Types.Result.DefaultSelection<Prisma.$ContactSettingsPayload>

export type AggregateContactSettings = {
  _count: ContactSettingsCountAggregateOutputType | null
  _avg: ContactSettingsAvgAggregateOutputType | null
  _sum: ContactSettingsSumAggregateOutputType | null
  _min: ContactSettingsMinAggregateOutputType | null
  _max: ContactSettingsMaxAggregateOutputType | null
}

export type ContactSettingsAvgAggregateOutputType = {
  id: number | null
  userId: number | null
  contactId: number | null
}

export type ContactSettingsSumAggregateOutputType = {
  id: number | null
  userId: number | null
  contactId: number | null
}

export type ContactSettingsMinAggregateOutputType = {
  id: number | null
  name: string | null
  recent_activity: string | null
  marked_as_read: boolean | null
  muted: boolean | null
  ignored: boolean | null
  archived: boolean | null
  pinned: boolean | null
  created_at: Date | null
  updated_at: Date | null
  deleted_at: Date | null
  userId: number | null
  contactId: number | null
}

export type ContactSettingsMaxAggregateOutputType = {
  id: number | null
  name: string | null
  recent_activity: string | null
  marked_as_read: boolean | null
  muted: boolean | null
  ignored: boolean | null
  archived: boolean | null
  pinned: boolean | null
  created_at: Date | null
  updated_at: Date | null
  deleted_at: Date | null
  userId: number | null
  contactId: number | null
}

export type ContactSettingsCountAggregateOutputType = {
  id: number
  name: number
  recent_activity: number
  marked_as_read: number
  muted: number
  ignored: number
  archived: number
  pinned: number
  created_at: number
  updated_at: number
  deleted_at: number
  userId: number
  contactId: number
  _all: number
}


export type ContactSettingsAvgAggregateInputType = {
  id?: true
  userId?: true
  contactId?: true
}

export type ContactSettingsSumAggregateInputType = {
  id?: true
  userId?: true
  contactId?: true
}

export type ContactSettingsMinAggregateInputType = {
  id?: true
  name?: true
  recent_activity?: true
  marked_as_read?: true
  muted?: true
  ignored?: true
  archived?: true
  pinned?: true
  created_at?: true
  updated_at?: true
  deleted_at?: true
  userId?: true
  contactId?: true
}

export type ContactSettingsMaxAggregateInputType = {
  id?: true
  name?: true
  recent_activity?: true
  marked_as_read?: true
  muted?: true
  ignored?: true
  archived?: true
  pinned?: true
  created_at?: true
  updated_at?: true
  deleted_at?: true
  userId?: true
  contactId?: true
}

export type ContactSettingsCountAggregateInputType = {
  id?: true
  name?: true
  recent_activity?: true
  marked_as_read?: true
  muted?: true
  ignored?: true
  archived?: true
  pinned?: true
  created_at?: true
  updated_at?: true
  deleted_at?: true
  userId?: true
  contactId?: true
  _all?: true
}

export type ContactSettingsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ContactSettings to aggregate.
   */
  where?: Prisma.ContactSettingsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ContactSettings to fetch.
   */
  orderBy?: Prisma.ContactSettingsOrderByWithRelationInput | Prisma.ContactSettingsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ContactSettingsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ContactSettings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ContactSettings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ContactSettings
  **/
  _count?: true | ContactSettingsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ContactSettingsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ContactSettingsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ContactSettingsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ContactSettingsMaxAggregateInputType
}

export type GetContactSettingsAggregateType<T extends ContactSettingsAggregateArgs> = {
      [P in keyof T & keyof AggregateContactSettings]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateContactSettings[P]>
    : Prisma.GetScalarType<T[P], AggregateContactSettings[P]>
}




export type ContactSettingsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ContactSettingsWhereInput
  orderBy?: Prisma.ContactSettingsOrderByWithAggregationInput | Prisma.ContactSettingsOrderByWithAggregationInput[]
  by: Prisma.ContactSettingsScalarFieldEnum[] | Prisma.ContactSettingsScalarFieldEnum
  having?: Prisma.ContactSettingsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ContactSettingsCountAggregateInputType | true
  _avg?: ContactSettingsAvgAggregateInputType
  _sum?: ContactSettingsSumAggregateInputType
  _min?: ContactSettingsMinAggregateInputType
  _max?: ContactSettingsMaxAggregateInputType
}

export type ContactSettingsGroupByOutputType = {
  id: number
  name: string | null
  recent_activity: string | null
  marked_as_read: boolean | null
  muted: boolean | null
  ignored: boolean | null
  archived: boolean | null
  pinned: boolean | null
  created_at: Date
  updated_at: Date
  deleted_at: Date | null
  userId: number
  contactId: number
  _count: ContactSettingsCountAggregateOutputType | null
  _avg: ContactSettingsAvgAggregateOutputType | null
  _sum: ContactSettingsSumAggregateOutputType | null
  _min: ContactSettingsMinAggregateOutputType | null
  _max: ContactSettingsMaxAggregateOutputType | null
}

type GetContactSettingsGroupByPayload<T extends ContactSettingsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ContactSettingsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ContactSettingsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ContactSettingsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ContactSettingsGroupByOutputType[P]>
      }
    >
  >



export type ContactSettingsWhereInput = {
  AND?: Prisma.ContactSettingsWhereInput | Prisma.ContactSettingsWhereInput[]
  OR?: Prisma.ContactSettingsWhereInput[]
  NOT?: Prisma.ContactSettingsWhereInput | Prisma.ContactSettingsWhereInput[]
  id?: Prisma.IntFilter<"ContactSettings"> | number
  name?: Prisma.StringNullableFilter<"ContactSettings"> | string | null
  recent_activity?: Prisma.StringNullableFilter<"ContactSettings"> | string | null
  marked_as_read?: Prisma.BoolNullableFilter<"ContactSettings"> | boolean | null
  muted?: Prisma.BoolNullableFilter<"ContactSettings"> | boolean | null
  ignored?: Prisma.BoolNullableFilter<"ContactSettings"> | boolean | null
  archived?: Prisma.BoolNullableFilter<"ContactSettings"> | boolean | null
  pinned?: Prisma.BoolNullableFilter<"ContactSettings"> | boolean | null
  created_at?: Prisma.DateTimeFilter<"ContactSettings"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"ContactSettings"> | Date | string
  deleted_at?: Prisma.DateTimeNullableFilter<"ContactSettings"> | Date | string | null
  userId?: Prisma.IntFilter<"ContactSettings"> | number
  contactId?: Prisma.IntFilter<"ContactSettings"> | number
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  contact?: Prisma.XOR<Prisma.ContactScalarRelationFilter, Prisma.ContactWhereInput>
}

export type ContactSettingsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrderInput | Prisma.SortOrder
  recent_activity?: Prisma.SortOrderInput | Prisma.SortOrder
  marked_as_read?: Prisma.SortOrderInput | Prisma.SortOrder
  muted?: Prisma.SortOrderInput | Prisma.SortOrder
  ignored?: Prisma.SortOrderInput | Prisma.SortOrder
  archived?: Prisma.SortOrderInput | Prisma.SortOrder
  pinned?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  deleted_at?: Prisma.SortOrderInput | Prisma.SortOrder
  userId?: Prisma.SortOrder
  contactId?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  contact?: Prisma.ContactOrderByWithRelationInput
  _relevance?: Prisma.ContactSettingsOrderByRelevanceInput
}

export type ContactSettingsWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  userId_contactId?: Prisma.ContactSettingsUserIdContactIdCompoundUniqueInput
  AND?: Prisma.ContactSettingsWhereInput | Prisma.ContactSettingsWhereInput[]
  OR?: Prisma.ContactSettingsWhereInput[]
  NOT?: Prisma.ContactSettingsWhereInput | Prisma.ContactSettingsWhereInput[]
  name?: Prisma.StringNullableFilter<"ContactSettings"> | string | null
  recent_activity?: Prisma.StringNullableFilter<"ContactSettings"> | string | null
  marked_as_read?: Prisma.BoolNullableFilter<"ContactSettings"> | boolean | null
  muted?: Prisma.BoolNullableFilter<"ContactSettings"> | boolean | null
  ignored?: Prisma.BoolNullableFilter<"ContactSettings"> | boolean | null
  archived?: Prisma.BoolNullableFilter<"ContactSettings"> | boolean | null
  pinned?: Prisma.BoolNullableFilter<"ContactSettings"> | boolean | null
  created_at?: Prisma.DateTimeFilter<"ContactSettings"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"ContactSettings"> | Date | string
  deleted_at?: Prisma.DateTimeNullableFilter<"ContactSettings"> | Date | string | null
  userId?: Prisma.IntFilter<"ContactSettings"> | number
  contactId?: Prisma.IntFilter<"ContactSettings"> | number
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  contact?: Prisma.XOR<Prisma.ContactScalarRelationFilter, Prisma.ContactWhereInput>
}, "id" | "userId_contactId">

export type ContactSettingsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrderInput | Prisma.SortOrder
  recent_activity?: Prisma.SortOrderInput | Prisma.SortOrder
  marked_as_read?: Prisma.SortOrderInput | Prisma.SortOrder
  muted?: Prisma.SortOrderInput | Prisma.SortOrder
  ignored?: Prisma.SortOrderInput | Prisma.SortOrder
  archived?: Prisma.SortOrderInput | Prisma.SortOrder
  pinned?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  deleted_at?: Prisma.SortOrderInput | Prisma.SortOrder
  userId?: Prisma.SortOrder
  contactId?: Prisma.SortOrder
  _count?: Prisma.ContactSettingsCountOrderByAggregateInput
  _avg?: Prisma.ContactSettingsAvgOrderByAggregateInput
  _max?: Prisma.ContactSettingsMaxOrderByAggregateInput
  _min?: Prisma.ContactSettingsMinOrderByAggregateInput
  _sum?: Prisma.ContactSettingsSumOrderByAggregateInput
}

export type ContactSettingsScalarWhereWithAggregatesInput = {
  AND?: Prisma.ContactSettingsScalarWhereWithAggregatesInput | Prisma.ContactSettingsScalarWhereWithAggregatesInput[]
  OR?: Prisma.ContactSettingsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ContactSettingsScalarWhereWithAggregatesInput | Prisma.ContactSettingsScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"ContactSettings"> | number
  name?: Prisma.StringNullableWithAggregatesFilter<"ContactSettings"> | string | null
  recent_activity?: Prisma.StringNullableWithAggregatesFilter<"ContactSettings"> | string | null
  marked_as_read?: Prisma.BoolNullableWithAggregatesFilter<"ContactSettings"> | boolean | null
  muted?: Prisma.BoolNullableWithAggregatesFilter<"ContactSettings"> | boolean | null
  ignored?: Prisma.BoolNullableWithAggregatesFilter<"ContactSettings"> | boolean | null
  archived?: Prisma.BoolNullableWithAggregatesFilter<"ContactSettings"> | boolean | null
  pinned?: Prisma.BoolNullableWithAggregatesFilter<"ContactSettings"> | boolean | null
  created_at?: Prisma.DateTimeWithAggregatesFilter<"ContactSettings"> | Date | string
  updated_at?: Prisma.DateTimeWithAggregatesFilter<"ContactSettings"> | Date | string
  deleted_at?: Prisma.DateTimeNullableWithAggregatesFilter<"ContactSettings"> | Date | string | null
  userId?: Prisma.IntWithAggregatesFilter<"ContactSettings"> | number
  contactId?: Prisma.IntWithAggregatesFilter<"ContactSettings"> | number
}

export type ContactSettingsCreateInput = {
  name?: string | null
  recent_activity?: string | null
  marked_as_read?: boolean | null
  muted?: boolean | null
  ignored?: boolean | null
  archived?: boolean | null
  pinned?: boolean | null
  created_at?: Date | string
  updated_at?: Date | string
  deleted_at?: Date | string | null
  user: Prisma.UserCreateNestedOneWithoutContactSettingsInput
  contact: Prisma.ContactCreateNestedOneWithoutContactSettingsInput
}

export type ContactSettingsUncheckedCreateInput = {
  id?: number
  name?: string | null
  recent_activity?: string | null
  marked_as_read?: boolean | null
  muted?: boolean | null
  ignored?: boolean | null
  archived?: boolean | null
  pinned?: boolean | null
  created_at?: Date | string
  updated_at?: Date | string
  deleted_at?: Date | string | null
  userId: number
  contactId: number
}

export type ContactSettingsUpdateInput = {
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  recent_activity?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  marked_as_read?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  muted?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  ignored?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  archived?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  pinned?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  user?: Prisma.UserUpdateOneRequiredWithoutContactSettingsNestedInput
  contact?: Prisma.ContactUpdateOneRequiredWithoutContactSettingsNestedInput
}

export type ContactSettingsUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  recent_activity?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  marked_as_read?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  muted?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  ignored?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  archived?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  pinned?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  contactId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type ContactSettingsCreateManyInput = {
  id?: number
  name?: string | null
  recent_activity?: string | null
  marked_as_read?: boolean | null
  muted?: boolean | null
  ignored?: boolean | null
  archived?: boolean | null
  pinned?: boolean | null
  created_at?: Date | string
  updated_at?: Date | string
  deleted_at?: Date | string | null
  userId: number
  contactId: number
}

export type ContactSettingsUpdateManyMutationInput = {
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  recent_activity?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  marked_as_read?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  muted?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  ignored?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  archived?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  pinned?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type ContactSettingsUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  recent_activity?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  marked_as_read?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  muted?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  ignored?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  archived?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  pinned?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  contactId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type ContactSettingsListRelationFilter = {
  every?: Prisma.ContactSettingsWhereInput
  some?: Prisma.ContactSettingsWhereInput
  none?: Prisma.ContactSettingsWhereInput
}

export type ContactSettingsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ContactSettingsOrderByRelevanceInput = {
  fields: Prisma.ContactSettingsOrderByRelevanceFieldEnum | Prisma.ContactSettingsOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type ContactSettingsUserIdContactIdCompoundUniqueInput = {
  userId: number
  contactId: number
}

export type ContactSettingsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  recent_activity?: Prisma.SortOrder
  marked_as_read?: Prisma.SortOrder
  muted?: Prisma.SortOrder
  ignored?: Prisma.SortOrder
  archived?: Prisma.SortOrder
  pinned?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  deleted_at?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  contactId?: Prisma.SortOrder
}

export type ContactSettingsAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  contactId?: Prisma.SortOrder
}

export type ContactSettingsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  recent_activity?: Prisma.SortOrder
  marked_as_read?: Prisma.SortOrder
  muted?: Prisma.SortOrder
  ignored?: Prisma.SortOrder
  archived?: Prisma.SortOrder
  pinned?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  deleted_at?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  contactId?: Prisma.SortOrder
}

export type ContactSettingsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  recent_activity?: Prisma.SortOrder
  marked_as_read?: Prisma.SortOrder
  muted?: Prisma.SortOrder
  ignored?: Prisma.SortOrder
  archived?: Prisma.SortOrder
  pinned?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  deleted_at?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  contactId?: Prisma.SortOrder
}

export type ContactSettingsSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  contactId?: Prisma.SortOrder
}

export type ContactSettingsCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.ContactSettingsCreateWithoutUserInput, Prisma.ContactSettingsUncheckedCreateWithoutUserInput> | Prisma.ContactSettingsCreateWithoutUserInput[] | Prisma.ContactSettingsUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ContactSettingsCreateOrConnectWithoutUserInput | Prisma.ContactSettingsCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.ContactSettingsCreateManyUserInputEnvelope
  connect?: Prisma.ContactSettingsWhereUniqueInput | Prisma.ContactSettingsWhereUniqueInput[]
}

export type ContactSettingsUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.ContactSettingsCreateWithoutUserInput, Prisma.ContactSettingsUncheckedCreateWithoutUserInput> | Prisma.ContactSettingsCreateWithoutUserInput[] | Prisma.ContactSettingsUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ContactSettingsCreateOrConnectWithoutUserInput | Prisma.ContactSettingsCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.ContactSettingsCreateManyUserInputEnvelope
  connect?: Prisma.ContactSettingsWhereUniqueInput | Prisma.ContactSettingsWhereUniqueInput[]
}

export type ContactSettingsUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.ContactSettingsCreateWithoutUserInput, Prisma.ContactSettingsUncheckedCreateWithoutUserInput> | Prisma.ContactSettingsCreateWithoutUserInput[] | Prisma.ContactSettingsUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ContactSettingsCreateOrConnectWithoutUserInput | Prisma.ContactSettingsCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.ContactSettingsUpsertWithWhereUniqueWithoutUserInput | Prisma.ContactSettingsUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.ContactSettingsCreateManyUserInputEnvelope
  set?: Prisma.ContactSettingsWhereUniqueInput | Prisma.ContactSettingsWhereUniqueInput[]
  disconnect?: Prisma.ContactSettingsWhereUniqueInput | Prisma.ContactSettingsWhereUniqueInput[]
  delete?: Prisma.ContactSettingsWhereUniqueInput | Prisma.ContactSettingsWhereUniqueInput[]
  connect?: Prisma.ContactSettingsWhereUniqueInput | Prisma.ContactSettingsWhereUniqueInput[]
  update?: Prisma.ContactSettingsUpdateWithWhereUniqueWithoutUserInput | Prisma.ContactSettingsUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.ContactSettingsUpdateManyWithWhereWithoutUserInput | Prisma.ContactSettingsUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.ContactSettingsScalarWhereInput | Prisma.ContactSettingsScalarWhereInput[]
}

export type ContactSettingsUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.ContactSettingsCreateWithoutUserInput, Prisma.ContactSettingsUncheckedCreateWithoutUserInput> | Prisma.ContactSettingsCreateWithoutUserInput[] | Prisma.ContactSettingsUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ContactSettingsCreateOrConnectWithoutUserInput | Prisma.ContactSettingsCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.ContactSettingsUpsertWithWhereUniqueWithoutUserInput | Prisma.ContactSettingsUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.ContactSettingsCreateManyUserInputEnvelope
  set?: Prisma.ContactSettingsWhereUniqueInput | Prisma.ContactSettingsWhereUniqueInput[]
  disconnect?: Prisma.ContactSettingsWhereUniqueInput | Prisma.ContactSettingsWhereUniqueInput[]
  delete?: Prisma.ContactSettingsWhereUniqueInput | Prisma.ContactSettingsWhereUniqueInput[]
  connect?: Prisma.ContactSettingsWhereUniqueInput | Prisma.ContactSettingsWhereUniqueInput[]
  update?: Prisma.ContactSettingsUpdateWithWhereUniqueWithoutUserInput | Prisma.ContactSettingsUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.ContactSettingsUpdateManyWithWhereWithoutUserInput | Prisma.ContactSettingsUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.ContactSettingsScalarWhereInput | Prisma.ContactSettingsScalarWhereInput[]
}

export type ContactSettingsCreateNestedManyWithoutContactInput = {
  create?: Prisma.XOR<Prisma.ContactSettingsCreateWithoutContactInput, Prisma.ContactSettingsUncheckedCreateWithoutContactInput> | Prisma.ContactSettingsCreateWithoutContactInput[] | Prisma.ContactSettingsUncheckedCreateWithoutContactInput[]
  connectOrCreate?: Prisma.ContactSettingsCreateOrConnectWithoutContactInput | Prisma.ContactSettingsCreateOrConnectWithoutContactInput[]
  createMany?: Prisma.ContactSettingsCreateManyContactInputEnvelope
  connect?: Prisma.ContactSettingsWhereUniqueInput | Prisma.ContactSettingsWhereUniqueInput[]
}

export type ContactSettingsUncheckedCreateNestedManyWithoutContactInput = {
  create?: Prisma.XOR<Prisma.ContactSettingsCreateWithoutContactInput, Prisma.ContactSettingsUncheckedCreateWithoutContactInput> | Prisma.ContactSettingsCreateWithoutContactInput[] | Prisma.ContactSettingsUncheckedCreateWithoutContactInput[]
  connectOrCreate?: Prisma.ContactSettingsCreateOrConnectWithoutContactInput | Prisma.ContactSettingsCreateOrConnectWithoutContactInput[]
  createMany?: Prisma.ContactSettingsCreateManyContactInputEnvelope
  connect?: Prisma.ContactSettingsWhereUniqueInput | Prisma.ContactSettingsWhereUniqueInput[]
}

export type ContactSettingsUpdateManyWithoutContactNestedInput = {
  create?: Prisma.XOR<Prisma.ContactSettingsCreateWithoutContactInput, Prisma.ContactSettingsUncheckedCreateWithoutContactInput> | Prisma.ContactSettingsCreateWithoutContactInput[] | Prisma.ContactSettingsUncheckedCreateWithoutContactInput[]
  connectOrCreate?: Prisma.ContactSettingsCreateOrConnectWithoutContactInput | Prisma.ContactSettingsCreateOrConnectWithoutContactInput[]
  upsert?: Prisma.ContactSettingsUpsertWithWhereUniqueWithoutContactInput | Prisma.ContactSettingsUpsertWithWhereUniqueWithoutContactInput[]
  createMany?: Prisma.ContactSettingsCreateManyContactInputEnvelope
  set?: Prisma.ContactSettingsWhereUniqueInput | Prisma.ContactSettingsWhereUniqueInput[]
  disconnect?: Prisma.ContactSettingsWhereUniqueInput | Prisma.ContactSettingsWhereUniqueInput[]
  delete?: Prisma.ContactSettingsWhereUniqueInput | Prisma.ContactSettingsWhereUniqueInput[]
  connect?: Prisma.ContactSettingsWhereUniqueInput | Prisma.ContactSettingsWhereUniqueInput[]
  update?: Prisma.ContactSettingsUpdateWithWhereUniqueWithoutContactInput | Prisma.ContactSettingsUpdateWithWhereUniqueWithoutContactInput[]
  updateMany?: Prisma.ContactSettingsUpdateManyWithWhereWithoutContactInput | Prisma.ContactSettingsUpdateManyWithWhereWithoutContactInput[]
  deleteMany?: Prisma.ContactSettingsScalarWhereInput | Prisma.ContactSettingsScalarWhereInput[]
}

export type ContactSettingsUncheckedUpdateManyWithoutContactNestedInput = {
  create?: Prisma.XOR<Prisma.ContactSettingsCreateWithoutContactInput, Prisma.ContactSettingsUncheckedCreateWithoutContactInput> | Prisma.ContactSettingsCreateWithoutContactInput[] | Prisma.ContactSettingsUncheckedCreateWithoutContactInput[]
  connectOrCreate?: Prisma.ContactSettingsCreateOrConnectWithoutContactInput | Prisma.ContactSettingsCreateOrConnectWithoutContactInput[]
  upsert?: Prisma.ContactSettingsUpsertWithWhereUniqueWithoutContactInput | Prisma.ContactSettingsUpsertWithWhereUniqueWithoutContactInput[]
  createMany?: Prisma.ContactSettingsCreateManyContactInputEnvelope
  set?: Prisma.ContactSettingsWhereUniqueInput | Prisma.ContactSettingsWhereUniqueInput[]
  disconnect?: Prisma.ContactSettingsWhereUniqueInput | Prisma.ContactSettingsWhereUniqueInput[]
  delete?: Prisma.ContactSettingsWhereUniqueInput | Prisma.ContactSettingsWhereUniqueInput[]
  connect?: Prisma.ContactSettingsWhereUniqueInput | Prisma.ContactSettingsWhereUniqueInput[]
  update?: Prisma.ContactSettingsUpdateWithWhereUniqueWithoutContactInput | Prisma.ContactSettingsUpdateWithWhereUniqueWithoutContactInput[]
  updateMany?: Prisma.ContactSettingsUpdateManyWithWhereWithoutContactInput | Prisma.ContactSettingsUpdateManyWithWhereWithoutContactInput[]
  deleteMany?: Prisma.ContactSettingsScalarWhereInput | Prisma.ContactSettingsScalarWhereInput[]
}

export type ContactSettingsCreateWithoutUserInput = {
  name?: string | null
  recent_activity?: string | null
  marked_as_read?: boolean | null
  muted?: boolean | null
  ignored?: boolean | null
  archived?: boolean | null
  pinned?: boolean | null
  created_at?: Date | string
  updated_at?: Date | string
  deleted_at?: Date | string | null
  contact: Prisma.ContactCreateNestedOneWithoutContactSettingsInput
}

export type ContactSettingsUncheckedCreateWithoutUserInput = {
  id?: number
  name?: string | null
  recent_activity?: string | null
  marked_as_read?: boolean | null
  muted?: boolean | null
  ignored?: boolean | null
  archived?: boolean | null
  pinned?: boolean | null
  created_at?: Date | string
  updated_at?: Date | string
  deleted_at?: Date | string | null
  contactId: number
}

export type ContactSettingsCreateOrConnectWithoutUserInput = {
  where: Prisma.ContactSettingsWhereUniqueInput
  create: Prisma.XOR<Prisma.ContactSettingsCreateWithoutUserInput, Prisma.ContactSettingsUncheckedCreateWithoutUserInput>
}

export type ContactSettingsCreateManyUserInputEnvelope = {
  data: Prisma.ContactSettingsCreateManyUserInput | Prisma.ContactSettingsCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type ContactSettingsUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.ContactSettingsWhereUniqueInput
  update: Prisma.XOR<Prisma.ContactSettingsUpdateWithoutUserInput, Prisma.ContactSettingsUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.ContactSettingsCreateWithoutUserInput, Prisma.ContactSettingsUncheckedCreateWithoutUserInput>
}

export type ContactSettingsUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.ContactSettingsWhereUniqueInput
  data: Prisma.XOR<Prisma.ContactSettingsUpdateWithoutUserInput, Prisma.ContactSettingsUncheckedUpdateWithoutUserInput>
}

export type ContactSettingsUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.ContactSettingsScalarWhereInput
  data: Prisma.XOR<Prisma.ContactSettingsUpdateManyMutationInput, Prisma.ContactSettingsUncheckedUpdateManyWithoutUserInput>
}

export type ContactSettingsScalarWhereInput = {
  AND?: Prisma.ContactSettingsScalarWhereInput | Prisma.ContactSettingsScalarWhereInput[]
  OR?: Prisma.ContactSettingsScalarWhereInput[]
  NOT?: Prisma.ContactSettingsScalarWhereInput | Prisma.ContactSettingsScalarWhereInput[]
  id?: Prisma.IntFilter<"ContactSettings"> | number
  name?: Prisma.StringNullableFilter<"ContactSettings"> | string | null
  recent_activity?: Prisma.StringNullableFilter<"ContactSettings"> | string | null
  marked_as_read?: Prisma.BoolNullableFilter<"ContactSettings"> | boolean | null
  muted?: Prisma.BoolNullableFilter<"ContactSettings"> | boolean | null
  ignored?: Prisma.BoolNullableFilter<"ContactSettings"> | boolean | null
  archived?: Prisma.BoolNullableFilter<"ContactSettings"> | boolean | null
  pinned?: Prisma.BoolNullableFilter<"ContactSettings"> | boolean | null
  created_at?: Prisma.DateTimeFilter<"ContactSettings"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"ContactSettings"> | Date | string
  deleted_at?: Prisma.DateTimeNullableFilter<"ContactSettings"> | Date | string | null
  userId?: Prisma.IntFilter<"ContactSettings"> | number
  contactId?: Prisma.IntFilter<"ContactSettings"> | number
}

export type ContactSettingsCreateWithoutContactInput = {
  name?: string | null
  recent_activity?: string | null
  marked_as_read?: boolean | null
  muted?: boolean | null
  ignored?: boolean | null
  archived?: boolean | null
  pinned?: boolean | null
  created_at?: Date | string
  updated_at?: Date | string
  deleted_at?: Date | string | null
  user: Prisma.UserCreateNestedOneWithoutContactSettingsInput
}

export type ContactSettingsUncheckedCreateWithoutContactInput = {
  id?: number
  name?: string | null
  recent_activity?: string | null
  marked_as_read?: boolean | null
  muted?: boolean | null
  ignored?: boolean | null
  archived?: boolean | null
  pinned?: boolean | null
  created_at?: Date | string
  updated_at?: Date | string
  deleted_at?: Date | string | null
  userId: number
}

export type ContactSettingsCreateOrConnectWithoutContactInput = {
  where: Prisma.ContactSettingsWhereUniqueInput
  create: Prisma.XOR<Prisma.ContactSettingsCreateWithoutContactInput, Prisma.ContactSettingsUncheckedCreateWithoutContactInput>
}

export type ContactSettingsCreateManyContactInputEnvelope = {
  data: Prisma.ContactSettingsCreateManyContactInput | Prisma.ContactSettingsCreateManyContactInput[]
  skipDuplicates?: boolean
}

export type ContactSettingsUpsertWithWhereUniqueWithoutContactInput = {
  where: Prisma.ContactSettingsWhereUniqueInput
  update: Prisma.XOR<Prisma.ContactSettingsUpdateWithoutContactInput, Prisma.ContactSettingsUncheckedUpdateWithoutContactInput>
  create: Prisma.XOR<Prisma.ContactSettingsCreateWithoutContactInput, Prisma.ContactSettingsUncheckedCreateWithoutContactInput>
}

export type ContactSettingsUpdateWithWhereUniqueWithoutContactInput = {
  where: Prisma.ContactSettingsWhereUniqueInput
  data: Prisma.XOR<Prisma.ContactSettingsUpdateWithoutContactInput, Prisma.ContactSettingsUncheckedUpdateWithoutContactInput>
}

export type ContactSettingsUpdateManyWithWhereWithoutContactInput = {
  where: Prisma.ContactSettingsScalarWhereInput
  data: Prisma.XOR<Prisma.ContactSettingsUpdateManyMutationInput, Prisma.ContactSettingsUncheckedUpdateManyWithoutContactInput>
}

export type ContactSettingsCreateManyUserInput = {
  id?: number
  name?: string | null
  recent_activity?: string | null
  marked_as_read?: boolean | null
  muted?: boolean | null
  ignored?: boolean | null
  archived?: boolean | null
  pinned?: boolean | null
  created_at?: Date | string
  updated_at?: Date | string
  deleted_at?: Date | string | null
  contactId: number
}

export type ContactSettingsUpdateWithoutUserInput = {
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  recent_activity?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  marked_as_read?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  muted?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  ignored?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  archived?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  pinned?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  contact?: Prisma.ContactUpdateOneRequiredWithoutContactSettingsNestedInput
}

export type ContactSettingsUncheckedUpdateWithoutUserInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  recent_activity?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  marked_as_read?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  muted?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  ignored?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  archived?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  pinned?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  contactId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type ContactSettingsUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  recent_activity?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  marked_as_read?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  muted?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  ignored?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  archived?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  pinned?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  contactId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type ContactSettingsCreateManyContactInput = {
  id?: number
  name?: string | null
  recent_activity?: string | null
  marked_as_read?: boolean | null
  muted?: boolean | null
  ignored?: boolean | null
  archived?: boolean | null
  pinned?: boolean | null
  created_at?: Date | string
  updated_at?: Date | string
  deleted_at?: Date | string | null
  userId: number
}

export type ContactSettingsUpdateWithoutContactInput = {
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  recent_activity?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  marked_as_read?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  muted?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  ignored?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  archived?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  pinned?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  user?: Prisma.UserUpdateOneRequiredWithoutContactSettingsNestedInput
}

export type ContactSettingsUncheckedUpdateWithoutContactInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  recent_activity?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  marked_as_read?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  muted?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  ignored?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  archived?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  pinned?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  userId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type ContactSettingsUncheckedUpdateManyWithoutContactInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  recent_activity?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  marked_as_read?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  muted?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  ignored?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  archived?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  pinned?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  userId?: Prisma.IntFieldUpdateOperationsInput | number
}



export type ContactSettingsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  recent_activity?: boolean
  marked_as_read?: boolean
  muted?: boolean
  ignored?: boolean
  archived?: boolean
  pinned?: boolean
  created_at?: boolean
  updated_at?: boolean
  deleted_at?: boolean
  userId?: boolean
  contactId?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  contact?: boolean | Prisma.ContactDefaultArgs<ExtArgs>
}, ExtArgs["result"]["contactSettings"]>

export type ContactSettingsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  recent_activity?: boolean
  marked_as_read?: boolean
  muted?: boolean
  ignored?: boolean
  archived?: boolean
  pinned?: boolean
  created_at?: boolean
  updated_at?: boolean
  deleted_at?: boolean
  userId?: boolean
  contactId?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  contact?: boolean | Prisma.ContactDefaultArgs<ExtArgs>
}, ExtArgs["result"]["contactSettings"]>

export type ContactSettingsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  recent_activity?: boolean
  marked_as_read?: boolean
  muted?: boolean
  ignored?: boolean
  archived?: boolean
  pinned?: boolean
  created_at?: boolean
  updated_at?: boolean
  deleted_at?: boolean
  userId?: boolean
  contactId?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  contact?: boolean | Prisma.ContactDefaultArgs<ExtArgs>
}, ExtArgs["result"]["contactSettings"]>

export type ContactSettingsSelectScalar = {
  id?: boolean
  name?: boolean
  recent_activity?: boolean
  marked_as_read?: boolean
  muted?: boolean
  ignored?: boolean
  archived?: boolean
  pinned?: boolean
  created_at?: boolean
  updated_at?: boolean
  deleted_at?: boolean
  userId?: boolean
  contactId?: boolean
}

export type ContactSettingsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "recent_activity" | "marked_as_read" | "muted" | "ignored" | "archived" | "pinned" | "created_at" | "updated_at" | "deleted_at" | "userId" | "contactId", ExtArgs["result"]["contactSettings"]>
export type ContactSettingsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  contact?: boolean | Prisma.ContactDefaultArgs<ExtArgs>
}
export type ContactSettingsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  contact?: boolean | Prisma.ContactDefaultArgs<ExtArgs>
}
export type ContactSettingsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  contact?: boolean | Prisma.ContactDefaultArgs<ExtArgs>
}

export type $ContactSettingsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ContactSettings"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
    contact: Prisma.$ContactPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    name: string | null
    recent_activity: string | null
    marked_as_read: boolean | null
    muted: boolean | null
    ignored: boolean | null
    archived: boolean | null
    pinned: boolean | null
    created_at: Date
    updated_at: Date
    deleted_at: Date | null
    userId: number
    contactId: number
  }, ExtArgs["result"]["contactSettings"]>
  composites: {}
}

export type ContactSettingsGetPayload<S extends boolean | null | undefined | ContactSettingsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ContactSettingsPayload, S>

export type ContactSettingsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ContactSettingsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ContactSettingsCountAggregateInputType | true
  }

export interface ContactSettingsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ContactSettings'], meta: { name: 'ContactSettings' } }
  /**
   * Find zero or one ContactSettings that matches the filter.
   * @param {ContactSettingsFindUniqueArgs} args - Arguments to find a ContactSettings
   * @example
   * // Get one ContactSettings
   * const contactSettings = await prisma.contactSettings.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ContactSettingsFindUniqueArgs>(args: Prisma.SelectSubset<T, ContactSettingsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ContactSettingsClient<runtime.Types.Result.GetResult<Prisma.$ContactSettingsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ContactSettings that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ContactSettingsFindUniqueOrThrowArgs} args - Arguments to find a ContactSettings
   * @example
   * // Get one ContactSettings
   * const contactSettings = await prisma.contactSettings.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ContactSettingsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ContactSettingsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ContactSettingsClient<runtime.Types.Result.GetResult<Prisma.$ContactSettingsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ContactSettings that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ContactSettingsFindFirstArgs} args - Arguments to find a ContactSettings
   * @example
   * // Get one ContactSettings
   * const contactSettings = await prisma.contactSettings.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ContactSettingsFindFirstArgs>(args?: Prisma.SelectSubset<T, ContactSettingsFindFirstArgs<ExtArgs>>): Prisma.Prisma__ContactSettingsClient<runtime.Types.Result.GetResult<Prisma.$ContactSettingsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ContactSettings that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ContactSettingsFindFirstOrThrowArgs} args - Arguments to find a ContactSettings
   * @example
   * // Get one ContactSettings
   * const contactSettings = await prisma.contactSettings.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ContactSettingsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ContactSettingsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ContactSettingsClient<runtime.Types.Result.GetResult<Prisma.$ContactSettingsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ContactSettings that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ContactSettingsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ContactSettings
   * const contactSettings = await prisma.contactSettings.findMany()
   * 
   * // Get first 10 ContactSettings
   * const contactSettings = await prisma.contactSettings.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const contactSettingsWithIdOnly = await prisma.contactSettings.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ContactSettingsFindManyArgs>(args?: Prisma.SelectSubset<T, ContactSettingsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ContactSettingsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ContactSettings.
   * @param {ContactSettingsCreateArgs} args - Arguments to create a ContactSettings.
   * @example
   * // Create one ContactSettings
   * const ContactSettings = await prisma.contactSettings.create({
   *   data: {
   *     // ... data to create a ContactSettings
   *   }
   * })
   * 
   */
  create<T extends ContactSettingsCreateArgs>(args: Prisma.SelectSubset<T, ContactSettingsCreateArgs<ExtArgs>>): Prisma.Prisma__ContactSettingsClient<runtime.Types.Result.GetResult<Prisma.$ContactSettingsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ContactSettings.
   * @param {ContactSettingsCreateManyArgs} args - Arguments to create many ContactSettings.
   * @example
   * // Create many ContactSettings
   * const contactSettings = await prisma.contactSettings.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ContactSettingsCreateManyArgs>(args?: Prisma.SelectSubset<T, ContactSettingsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ContactSettings and returns the data saved in the database.
   * @param {ContactSettingsCreateManyAndReturnArgs} args - Arguments to create many ContactSettings.
   * @example
   * // Create many ContactSettings
   * const contactSettings = await prisma.contactSettings.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ContactSettings and only return the `id`
   * const contactSettingsWithIdOnly = await prisma.contactSettings.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ContactSettingsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ContactSettingsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ContactSettingsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ContactSettings.
   * @param {ContactSettingsDeleteArgs} args - Arguments to delete one ContactSettings.
   * @example
   * // Delete one ContactSettings
   * const ContactSettings = await prisma.contactSettings.delete({
   *   where: {
   *     // ... filter to delete one ContactSettings
   *   }
   * })
   * 
   */
  delete<T extends ContactSettingsDeleteArgs>(args: Prisma.SelectSubset<T, ContactSettingsDeleteArgs<ExtArgs>>): Prisma.Prisma__ContactSettingsClient<runtime.Types.Result.GetResult<Prisma.$ContactSettingsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ContactSettings.
   * @param {ContactSettingsUpdateArgs} args - Arguments to update one ContactSettings.
   * @example
   * // Update one ContactSettings
   * const contactSettings = await prisma.contactSettings.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ContactSettingsUpdateArgs>(args: Prisma.SelectSubset<T, ContactSettingsUpdateArgs<ExtArgs>>): Prisma.Prisma__ContactSettingsClient<runtime.Types.Result.GetResult<Prisma.$ContactSettingsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ContactSettings.
   * @param {ContactSettingsDeleteManyArgs} args - Arguments to filter ContactSettings to delete.
   * @example
   * // Delete a few ContactSettings
   * const { count } = await prisma.contactSettings.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ContactSettingsDeleteManyArgs>(args?: Prisma.SelectSubset<T, ContactSettingsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ContactSettings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ContactSettingsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ContactSettings
   * const contactSettings = await prisma.contactSettings.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ContactSettingsUpdateManyArgs>(args: Prisma.SelectSubset<T, ContactSettingsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ContactSettings and returns the data updated in the database.
   * @param {ContactSettingsUpdateManyAndReturnArgs} args - Arguments to update many ContactSettings.
   * @example
   * // Update many ContactSettings
   * const contactSettings = await prisma.contactSettings.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ContactSettings and only return the `id`
   * const contactSettingsWithIdOnly = await prisma.contactSettings.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ContactSettingsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ContactSettingsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ContactSettingsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ContactSettings.
   * @param {ContactSettingsUpsertArgs} args - Arguments to update or create a ContactSettings.
   * @example
   * // Update or create a ContactSettings
   * const contactSettings = await prisma.contactSettings.upsert({
   *   create: {
   *     // ... data to create a ContactSettings
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ContactSettings we want to update
   *   }
   * })
   */
  upsert<T extends ContactSettingsUpsertArgs>(args: Prisma.SelectSubset<T, ContactSettingsUpsertArgs<ExtArgs>>): Prisma.Prisma__ContactSettingsClient<runtime.Types.Result.GetResult<Prisma.$ContactSettingsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ContactSettings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ContactSettingsCountArgs} args - Arguments to filter ContactSettings to count.
   * @example
   * // Count the number of ContactSettings
   * const count = await prisma.contactSettings.count({
   *   where: {
   *     // ... the filter for the ContactSettings we want to count
   *   }
   * })
  **/
  count<T extends ContactSettingsCountArgs>(
    args?: Prisma.Subset<T, ContactSettingsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ContactSettingsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ContactSettings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ContactSettingsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ContactSettingsAggregateArgs>(args: Prisma.Subset<T, ContactSettingsAggregateArgs>): Prisma.PrismaPromise<GetContactSettingsAggregateType<T>>

  /**
   * Group by ContactSettings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ContactSettingsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ContactSettingsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ContactSettingsGroupByArgs['orderBy'] }
      : { orderBy?: ContactSettingsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ContactSettingsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetContactSettingsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ContactSettings model
 */
readonly fields: ContactSettingsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ContactSettings.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ContactSettingsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  contact<T extends Prisma.ContactDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ContactDefaultArgs<ExtArgs>>): Prisma.Prisma__ContactClient<runtime.Types.Result.GetResult<Prisma.$ContactPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ContactSettings model
 */
export interface ContactSettingsFieldRefs {
  readonly id: Prisma.FieldRef<"ContactSettings", 'Int'>
  readonly name: Prisma.FieldRef<"ContactSettings", 'String'>
  readonly recent_activity: Prisma.FieldRef<"ContactSettings", 'String'>
  readonly marked_as_read: Prisma.FieldRef<"ContactSettings", 'Boolean'>
  readonly muted: Prisma.FieldRef<"ContactSettings", 'Boolean'>
  readonly ignored: Prisma.FieldRef<"ContactSettings", 'Boolean'>
  readonly archived: Prisma.FieldRef<"ContactSettings", 'Boolean'>
  readonly pinned: Prisma.FieldRef<"ContactSettings", 'Boolean'>
  readonly created_at: Prisma.FieldRef<"ContactSettings", 'DateTime'>
  readonly updated_at: Prisma.FieldRef<"ContactSettings", 'DateTime'>
  readonly deleted_at: Prisma.FieldRef<"ContactSettings", 'DateTime'>
  readonly userId: Prisma.FieldRef<"ContactSettings", 'Int'>
  readonly contactId: Prisma.FieldRef<"ContactSettings", 'Int'>
}
    

// Custom InputTypes
/**
 * ContactSettings findUnique
 */
export type ContactSettingsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ContactSettings
   */
  select?: Prisma.ContactSettingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ContactSettings
   */
  omit?: Prisma.ContactSettingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContactSettingsInclude<ExtArgs> | null
  /**
   * Filter, which ContactSettings to fetch.
   */
  where: Prisma.ContactSettingsWhereUniqueInput
}

/**
 * ContactSettings findUniqueOrThrow
 */
export type ContactSettingsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ContactSettings
   */
  select?: Prisma.ContactSettingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ContactSettings
   */
  omit?: Prisma.ContactSettingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContactSettingsInclude<ExtArgs> | null
  /**
   * Filter, which ContactSettings to fetch.
   */
  where: Prisma.ContactSettingsWhereUniqueInput
}

/**
 * ContactSettings findFirst
 */
export type ContactSettingsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ContactSettings
   */
  select?: Prisma.ContactSettingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ContactSettings
   */
  omit?: Prisma.ContactSettingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContactSettingsInclude<ExtArgs> | null
  /**
   * Filter, which ContactSettings to fetch.
   */
  where?: Prisma.ContactSettingsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ContactSettings to fetch.
   */
  orderBy?: Prisma.ContactSettingsOrderByWithRelationInput | Prisma.ContactSettingsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ContactSettings.
   */
  cursor?: Prisma.ContactSettingsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ContactSettings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ContactSettings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ContactSettings.
   */
  distinct?: Prisma.ContactSettingsScalarFieldEnum | Prisma.ContactSettingsScalarFieldEnum[]
}

/**
 * ContactSettings findFirstOrThrow
 */
export type ContactSettingsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ContactSettings
   */
  select?: Prisma.ContactSettingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ContactSettings
   */
  omit?: Prisma.ContactSettingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContactSettingsInclude<ExtArgs> | null
  /**
   * Filter, which ContactSettings to fetch.
   */
  where?: Prisma.ContactSettingsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ContactSettings to fetch.
   */
  orderBy?: Prisma.ContactSettingsOrderByWithRelationInput | Prisma.ContactSettingsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ContactSettings.
   */
  cursor?: Prisma.ContactSettingsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ContactSettings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ContactSettings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ContactSettings.
   */
  distinct?: Prisma.ContactSettingsScalarFieldEnum | Prisma.ContactSettingsScalarFieldEnum[]
}

/**
 * ContactSettings findMany
 */
export type ContactSettingsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ContactSettings
   */
  select?: Prisma.ContactSettingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ContactSettings
   */
  omit?: Prisma.ContactSettingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContactSettingsInclude<ExtArgs> | null
  /**
   * Filter, which ContactSettings to fetch.
   */
  where?: Prisma.ContactSettingsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ContactSettings to fetch.
   */
  orderBy?: Prisma.ContactSettingsOrderByWithRelationInput | Prisma.ContactSettingsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ContactSettings.
   */
  cursor?: Prisma.ContactSettingsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ContactSettings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ContactSettings.
   */
  skip?: number
  distinct?: Prisma.ContactSettingsScalarFieldEnum | Prisma.ContactSettingsScalarFieldEnum[]
}

/**
 * ContactSettings create
 */
export type ContactSettingsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ContactSettings
   */
  select?: Prisma.ContactSettingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ContactSettings
   */
  omit?: Prisma.ContactSettingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContactSettingsInclude<ExtArgs> | null
  /**
   * The data needed to create a ContactSettings.
   */
  data: Prisma.XOR<Prisma.ContactSettingsCreateInput, Prisma.ContactSettingsUncheckedCreateInput>
}

/**
 * ContactSettings createMany
 */
export type ContactSettingsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ContactSettings.
   */
  data: Prisma.ContactSettingsCreateManyInput | Prisma.ContactSettingsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ContactSettings createManyAndReturn
 */
export type ContactSettingsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ContactSettings
   */
  select?: Prisma.ContactSettingsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ContactSettings
   */
  omit?: Prisma.ContactSettingsOmit<ExtArgs> | null
  /**
   * The data used to create many ContactSettings.
   */
  data: Prisma.ContactSettingsCreateManyInput | Prisma.ContactSettingsCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContactSettingsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ContactSettings update
 */
export type ContactSettingsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ContactSettings
   */
  select?: Prisma.ContactSettingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ContactSettings
   */
  omit?: Prisma.ContactSettingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContactSettingsInclude<ExtArgs> | null
  /**
   * The data needed to update a ContactSettings.
   */
  data: Prisma.XOR<Prisma.ContactSettingsUpdateInput, Prisma.ContactSettingsUncheckedUpdateInput>
  /**
   * Choose, which ContactSettings to update.
   */
  where: Prisma.ContactSettingsWhereUniqueInput
}

/**
 * ContactSettings updateMany
 */
export type ContactSettingsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ContactSettings.
   */
  data: Prisma.XOR<Prisma.ContactSettingsUpdateManyMutationInput, Prisma.ContactSettingsUncheckedUpdateManyInput>
  /**
   * Filter which ContactSettings to update
   */
  where?: Prisma.ContactSettingsWhereInput
  /**
   * Limit how many ContactSettings to update.
   */
  limit?: number
}

/**
 * ContactSettings updateManyAndReturn
 */
export type ContactSettingsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ContactSettings
   */
  select?: Prisma.ContactSettingsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ContactSettings
   */
  omit?: Prisma.ContactSettingsOmit<ExtArgs> | null
  /**
   * The data used to update ContactSettings.
   */
  data: Prisma.XOR<Prisma.ContactSettingsUpdateManyMutationInput, Prisma.ContactSettingsUncheckedUpdateManyInput>
  /**
   * Filter which ContactSettings to update
   */
  where?: Prisma.ContactSettingsWhereInput
  /**
   * Limit how many ContactSettings to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContactSettingsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ContactSettings upsert
 */
export type ContactSettingsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ContactSettings
   */
  select?: Prisma.ContactSettingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ContactSettings
   */
  omit?: Prisma.ContactSettingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContactSettingsInclude<ExtArgs> | null
  /**
   * The filter to search for the ContactSettings to update in case it exists.
   */
  where: Prisma.ContactSettingsWhereUniqueInput
  /**
   * In case the ContactSettings found by the `where` argument doesn't exist, create a new ContactSettings with this data.
   */
  create: Prisma.XOR<Prisma.ContactSettingsCreateInput, Prisma.ContactSettingsUncheckedCreateInput>
  /**
   * In case the ContactSettings was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ContactSettingsUpdateInput, Prisma.ContactSettingsUncheckedUpdateInput>
}

/**
 * ContactSettings delete
 */
export type ContactSettingsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ContactSettings
   */
  select?: Prisma.ContactSettingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ContactSettings
   */
  omit?: Prisma.ContactSettingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContactSettingsInclude<ExtArgs> | null
  /**
   * Filter which ContactSettings to delete.
   */
  where: Prisma.ContactSettingsWhereUniqueInput
}

/**
 * ContactSettings deleteMany
 */
export type ContactSettingsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ContactSettings to delete
   */
  where?: Prisma.ContactSettingsWhereInput
  /**
   * Limit how many ContactSettings to delete.
   */
  limit?: number
}

/**
 * ContactSettings without action
 */
export type ContactSettingsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ContactSettings
   */
  select?: Prisma.ContactSettingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ContactSettings
   */
  omit?: Prisma.ContactSettingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContactSettingsInclude<ExtArgs> | null
}
