
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Contact` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Contact
 * 
 */
export type ContactModel = runtime.Types.Result.DefaultSelection<Prisma.$ContactPayload>

export type AggregateContact = {
  _count: ContactCountAggregateOutputType | null
  _avg: ContactAvgAggregateOutputType | null
  _sum: ContactSumAggregateOutputType | null
  _min: ContactMinAggregateOutputType | null
  _max: ContactMaxAggregateOutputType | null
}

export type ContactAvgAggregateOutputType = {
  id: number | null
}

export type ContactSumAggregateOutputType = {
  id: number | null
}

export type ContactMinAggregateOutputType = {
  id: number | null
  name: string | null
  recent_activity: string | null
  status: string | null
  avatar: string | null
  type: string | null
  created_at: Date | null
  updated_at: Date | null
  deleted_at: Date | null
}

export type ContactMaxAggregateOutputType = {
  id: number | null
  name: string | null
  recent_activity: string | null
  status: string | null
  avatar: string | null
  type: string | null
  created_at: Date | null
  updated_at: Date | null
  deleted_at: Date | null
}

export type ContactCountAggregateOutputType = {
  id: number
  name: number
  recent_activity: number
  status: number
  avatar: number
  type: number
  created_at: number
  updated_at: number
  deleted_at: number
  _all: number
}


export type ContactAvgAggregateInputType = {
  id?: true
}

export type ContactSumAggregateInputType = {
  id?: true
}

export type ContactMinAggregateInputType = {
  id?: true
  name?: true
  recent_activity?: true
  status?: true
  avatar?: true
  type?: true
  created_at?: true
  updated_at?: true
  deleted_at?: true
}

export type ContactMaxAggregateInputType = {
  id?: true
  name?: true
  recent_activity?: true
  status?: true
  avatar?: true
  type?: true
  created_at?: true
  updated_at?: true
  deleted_at?: true
}

export type ContactCountAggregateInputType = {
  id?: true
  name?: true
  recent_activity?: true
  status?: true
  avatar?: true
  type?: true
  created_at?: true
  updated_at?: true
  deleted_at?: true
  _all?: true
}

export type ContactAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Contact to aggregate.
   */
  where?: Prisma.ContactWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Contacts to fetch.
   */
  orderBy?: Prisma.ContactOrderByWithRelationInput | Prisma.ContactOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ContactWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Contacts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Contacts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Contacts
  **/
  _count?: true | ContactCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ContactAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ContactSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ContactMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ContactMaxAggregateInputType
}

export type GetContactAggregateType<T extends ContactAggregateArgs> = {
      [P in keyof T & keyof AggregateContact]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateContact[P]>
    : Prisma.GetScalarType<T[P], AggregateContact[P]>
}




export type ContactGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ContactWhereInput
  orderBy?: Prisma.ContactOrderByWithAggregationInput | Prisma.ContactOrderByWithAggregationInput[]
  by: Prisma.ContactScalarFieldEnum[] | Prisma.ContactScalarFieldEnum
  having?: Prisma.ContactScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ContactCountAggregateInputType | true
  _avg?: ContactAvgAggregateInputType
  _sum?: ContactSumAggregateInputType
  _min?: ContactMinAggregateInputType
  _max?: ContactMaxAggregateInputType
}

export type ContactGroupByOutputType = {
  id: number
  name: string
  recent_activity: string | null
  status: string | null
  avatar: string | null
  type: string | null
  created_at: Date
  updated_at: Date
  deleted_at: Date | null
  _count: ContactCountAggregateOutputType | null
  _avg: ContactAvgAggregateOutputType | null
  _sum: ContactSumAggregateOutputType | null
  _min: ContactMinAggregateOutputType | null
  _max: ContactMaxAggregateOutputType | null
}

type GetContactGroupByPayload<T extends ContactGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ContactGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ContactGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ContactGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ContactGroupByOutputType[P]>
      }
    >
  >



export type ContactWhereInput = {
  AND?: Prisma.ContactWhereInput | Prisma.ContactWhereInput[]
  OR?: Prisma.ContactWhereInput[]
  NOT?: Prisma.ContactWhereInput | Prisma.ContactWhereInput[]
  id?: Prisma.IntFilter<"Contact"> | number
  name?: Prisma.StringFilter<"Contact"> | string
  recent_activity?: Prisma.StringNullableFilter<"Contact"> | string | null
  status?: Prisma.StringNullableFilter<"Contact"> | string | null
  avatar?: Prisma.StringNullableFilter<"Contact"> | string | null
  type?: Prisma.StringNullableFilter<"Contact"> | string | null
  created_at?: Prisma.DateTimeFilter<"Contact"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"Contact"> | Date | string
  deleted_at?: Prisma.DateTimeNullableFilter<"Contact"> | Date | string | null
  users?: Prisma.UserListRelationFilter
  messages?: Prisma.MessageListRelationFilter
  contactRequests?: Prisma.ContactRequestListRelationFilter
  contactSettings?: Prisma.ContactSettingsListRelationFilter
}

export type ContactOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  recent_activity?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrderInput | Prisma.SortOrder
  avatar?: Prisma.SortOrderInput | Prisma.SortOrder
  type?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  deleted_at?: Prisma.SortOrderInput | Prisma.SortOrder
  users?: Prisma.UserOrderByRelationAggregateInput
  messages?: Prisma.MessageOrderByRelationAggregateInput
  contactRequests?: Prisma.ContactRequestOrderByRelationAggregateInput
  contactSettings?: Prisma.ContactSettingsOrderByRelationAggregateInput
  _relevance?: Prisma.ContactOrderByRelevanceInput
}

export type ContactWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.ContactWhereInput | Prisma.ContactWhereInput[]
  OR?: Prisma.ContactWhereInput[]
  NOT?: Prisma.ContactWhereInput | Prisma.ContactWhereInput[]
  name?: Prisma.StringFilter<"Contact"> | string
  recent_activity?: Prisma.StringNullableFilter<"Contact"> | string | null
  status?: Prisma.StringNullableFilter<"Contact"> | string | null
  avatar?: Prisma.StringNullableFilter<"Contact"> | string | null
  type?: Prisma.StringNullableFilter<"Contact"> | string | null
  created_at?: Prisma.DateTimeFilter<"Contact"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"Contact"> | Date | string
  deleted_at?: Prisma.DateTimeNullableFilter<"Contact"> | Date | string | null
  users?: Prisma.UserListRelationFilter
  messages?: Prisma.MessageListRelationFilter
  contactRequests?: Prisma.ContactRequestListRelationFilter
  contactSettings?: Prisma.ContactSettingsListRelationFilter
}, "id">

export type ContactOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  recent_activity?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrderInput | Prisma.SortOrder
  avatar?: Prisma.SortOrderInput | Prisma.SortOrder
  type?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  deleted_at?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.ContactCountOrderByAggregateInput
  _avg?: Prisma.ContactAvgOrderByAggregateInput
  _max?: Prisma.ContactMaxOrderByAggregateInput
  _min?: Prisma.ContactMinOrderByAggregateInput
  _sum?: Prisma.ContactSumOrderByAggregateInput
}

export type ContactScalarWhereWithAggregatesInput = {
  AND?: Prisma.ContactScalarWhereWithAggregatesInput | Prisma.ContactScalarWhereWithAggregatesInput[]
  OR?: Prisma.ContactScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ContactScalarWhereWithAggregatesInput | Prisma.ContactScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Contact"> | number
  name?: Prisma.StringWithAggregatesFilter<"Contact"> | string
  recent_activity?: Prisma.StringNullableWithAggregatesFilter<"Contact"> | string | null
  status?: Prisma.StringNullableWithAggregatesFilter<"Contact"> | string | null
  avatar?: Prisma.StringNullableWithAggregatesFilter<"Contact"> | string | null
  type?: Prisma.StringNullableWithAggregatesFilter<"Contact"> | string | null
  created_at?: Prisma.DateTimeWithAggregatesFilter<"Contact"> | Date | string
  updated_at?: Prisma.DateTimeWithAggregatesFilter<"Contact"> | Date | string
  deleted_at?: Prisma.DateTimeNullableWithAggregatesFilter<"Contact"> | Date | string | null
}

export type ContactCreateInput = {
  name: string
  recent_activity?: string | null
  status?: string | null
  avatar?: string | null
  type?: string | null
  created_at?: Date | string
  updated_at?: Date | string
  deleted_at?: Date | string | null
  users?: Prisma.UserCreateNestedManyWithoutContactsInput
  messages?: Prisma.MessageCreateNestedManyWithoutContactInput
  contactRequests?: Prisma.ContactRequestCreateNestedManyWithoutContactInput
  contactSettings?: Prisma.ContactSettingsCreateNestedManyWithoutContactInput
}

export type ContactUncheckedCreateInput = {
  id?: number
  name: string
  recent_activity?: string | null
  status?: string | null
  avatar?: string | null
  type?: string | null
  created_at?: Date | string
  updated_at?: Date | string
  deleted_at?: Date | string | null
  users?: Prisma.UserUncheckedCreateNestedManyWithoutContactsInput
  messages?: Prisma.MessageUncheckedCreateNestedManyWithoutContactInput
  contactRequests?: Prisma.ContactRequestUncheckedCreateNestedManyWithoutContactInput
  contactSettings?: Prisma.ContactSettingsUncheckedCreateNestedManyWithoutContactInput
}

export type ContactUpdateInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  recent_activity?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  avatar?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  users?: Prisma.UserUpdateManyWithoutContactsNestedInput
  messages?: Prisma.MessageUpdateManyWithoutContactNestedInput
  contactRequests?: Prisma.ContactRequestUpdateManyWithoutContactNestedInput
  contactSettings?: Prisma.ContactSettingsUpdateManyWithoutContactNestedInput
}

export type ContactUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  recent_activity?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  avatar?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  users?: Prisma.UserUncheckedUpdateManyWithoutContactsNestedInput
  messages?: Prisma.MessageUncheckedUpdateManyWithoutContactNestedInput
  contactRequests?: Prisma.ContactRequestUncheckedUpdateManyWithoutContactNestedInput
  contactSettings?: Prisma.ContactSettingsUncheckedUpdateManyWithoutContactNestedInput
}

export type ContactCreateManyInput = {
  id?: number
  name: string
  recent_activity?: string | null
  status?: string | null
  avatar?: string | null
  type?: string | null
  created_at?: Date | string
  updated_at?: Date | string
  deleted_at?: Date | string | null
}

export type ContactUpdateManyMutationInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  recent_activity?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  avatar?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type ContactUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  recent_activity?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  avatar?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type ContactListRelationFilter = {
  every?: Prisma.ContactWhereInput
  some?: Prisma.ContactWhereInput
  none?: Prisma.ContactWhereInput
}

export type ContactOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ContactNullableScalarRelationFilter = {
  is?: Prisma.ContactWhereInput | null
  isNot?: Prisma.ContactWhereInput | null
}

export type ContactOrderByRelevanceInput = {
  fields: Prisma.ContactOrderByRelevanceFieldEnum | Prisma.ContactOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type ContactCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  recent_activity?: Prisma.SortOrder
  status?: Prisma.SortOrder
  avatar?: Prisma.SortOrder
  type?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  deleted_at?: Prisma.SortOrder
}

export type ContactAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type ContactMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  recent_activity?: Prisma.SortOrder
  status?: Prisma.SortOrder
  avatar?: Prisma.SortOrder
  type?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  deleted_at?: Prisma.SortOrder
}

export type ContactMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  recent_activity?: Prisma.SortOrder
  status?: Prisma.SortOrder
  avatar?: Prisma.SortOrder
  type?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  deleted_at?: Prisma.SortOrder
}

export type ContactSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type ContactScalarRelationFilter = {
  is?: Prisma.ContactWhereInput
  isNot?: Prisma.ContactWhereInput
}

export type ContactCreateNestedManyWithoutUsersInput = {
  create?: Prisma.XOR<Prisma.ContactCreateWithoutUsersInput, Prisma.ContactUncheckedCreateWithoutUsersInput> | Prisma.ContactCreateWithoutUsersInput[] | Prisma.ContactUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.ContactCreateOrConnectWithoutUsersInput | Prisma.ContactCreateOrConnectWithoutUsersInput[]
  connect?: Prisma.ContactWhereUniqueInput | Prisma.ContactWhereUniqueInput[]
}

export type ContactUncheckedCreateNestedManyWithoutUsersInput = {
  create?: Prisma.XOR<Prisma.ContactCreateWithoutUsersInput, Prisma.ContactUncheckedCreateWithoutUsersInput> | Prisma.ContactCreateWithoutUsersInput[] | Prisma.ContactUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.ContactCreateOrConnectWithoutUsersInput | Prisma.ContactCreateOrConnectWithoutUsersInput[]
  connect?: Prisma.ContactWhereUniqueInput | Prisma.ContactWhereUniqueInput[]
}

export type ContactUpdateManyWithoutUsersNestedInput = {
  create?: Prisma.XOR<Prisma.ContactCreateWithoutUsersInput, Prisma.ContactUncheckedCreateWithoutUsersInput> | Prisma.ContactCreateWithoutUsersInput[] | Prisma.ContactUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.ContactCreateOrConnectWithoutUsersInput | Prisma.ContactCreateOrConnectWithoutUsersInput[]
  upsert?: Prisma.ContactUpsertWithWhereUniqueWithoutUsersInput | Prisma.ContactUpsertWithWhereUniqueWithoutUsersInput[]
  set?: Prisma.ContactWhereUniqueInput | Prisma.ContactWhereUniqueInput[]
  disconnect?: Prisma.ContactWhereUniqueInput | Prisma.ContactWhereUniqueInput[]
  delete?: Prisma.ContactWhereUniqueInput | Prisma.ContactWhereUniqueInput[]
  connect?: Prisma.ContactWhereUniqueInput | Prisma.ContactWhereUniqueInput[]
  update?: Prisma.ContactUpdateWithWhereUniqueWithoutUsersInput | Prisma.ContactUpdateWithWhereUniqueWithoutUsersInput[]
  updateMany?: Prisma.ContactUpdateManyWithWhereWithoutUsersInput | Prisma.ContactUpdateManyWithWhereWithoutUsersInput[]
  deleteMany?: Prisma.ContactScalarWhereInput | Prisma.ContactScalarWhereInput[]
}

export type ContactUncheckedUpdateManyWithoutUsersNestedInput = {
  create?: Prisma.XOR<Prisma.ContactCreateWithoutUsersInput, Prisma.ContactUncheckedCreateWithoutUsersInput> | Prisma.ContactCreateWithoutUsersInput[] | Prisma.ContactUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.ContactCreateOrConnectWithoutUsersInput | Prisma.ContactCreateOrConnectWithoutUsersInput[]
  upsert?: Prisma.ContactUpsertWithWhereUniqueWithoutUsersInput | Prisma.ContactUpsertWithWhereUniqueWithoutUsersInput[]
  set?: Prisma.ContactWhereUniqueInput | Prisma.ContactWhereUniqueInput[]
  disconnect?: Prisma.ContactWhereUniqueInput | Prisma.ContactWhereUniqueInput[]
  delete?: Prisma.ContactWhereUniqueInput | Prisma.ContactWhereUniqueInput[]
  connect?: Prisma.ContactWhereUniqueInput | Prisma.ContactWhereUniqueInput[]
  update?: Prisma.ContactUpdateWithWhereUniqueWithoutUsersInput | Prisma.ContactUpdateWithWhereUniqueWithoutUsersInput[]
  updateMany?: Prisma.ContactUpdateManyWithWhereWithoutUsersInput | Prisma.ContactUpdateManyWithWhereWithoutUsersInput[]
  deleteMany?: Prisma.ContactScalarWhereInput | Prisma.ContactScalarWhereInput[]
}

export type ContactCreateNestedOneWithoutMessagesInput = {
  create?: Prisma.XOR<Prisma.ContactCreateWithoutMessagesInput, Prisma.ContactUncheckedCreateWithoutMessagesInput>
  connectOrCreate?: Prisma.ContactCreateOrConnectWithoutMessagesInput
  connect?: Prisma.ContactWhereUniqueInput
}

export type ContactUpdateOneWithoutMessagesNestedInput = {
  create?: Prisma.XOR<Prisma.ContactCreateWithoutMessagesInput, Prisma.ContactUncheckedCreateWithoutMessagesInput>
  connectOrCreate?: Prisma.ContactCreateOrConnectWithoutMessagesInput
  upsert?: Prisma.ContactUpsertWithoutMessagesInput
  disconnect?: Prisma.ContactWhereInput | boolean
  delete?: Prisma.ContactWhereInput | boolean
  connect?: Prisma.ContactWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ContactUpdateToOneWithWhereWithoutMessagesInput, Prisma.ContactUpdateWithoutMessagesInput>, Prisma.ContactUncheckedUpdateWithoutMessagesInput>
}

export type ContactCreateNestedOneWithoutContactRequestsInput = {
  create?: Prisma.XOR<Prisma.ContactCreateWithoutContactRequestsInput, Prisma.ContactUncheckedCreateWithoutContactRequestsInput>
  connectOrCreate?: Prisma.ContactCreateOrConnectWithoutContactRequestsInput
  connect?: Prisma.ContactWhereUniqueInput
}

export type ContactUpdateOneRequiredWithoutContactRequestsNestedInput = {
  create?: Prisma.XOR<Prisma.ContactCreateWithoutContactRequestsInput, Prisma.ContactUncheckedCreateWithoutContactRequestsInput>
  connectOrCreate?: Prisma.ContactCreateOrConnectWithoutContactRequestsInput
  upsert?: Prisma.ContactUpsertWithoutContactRequestsInput
  connect?: Prisma.ContactWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ContactUpdateToOneWithWhereWithoutContactRequestsInput, Prisma.ContactUpdateWithoutContactRequestsInput>, Prisma.ContactUncheckedUpdateWithoutContactRequestsInput>
}

export type ContactCreateNestedOneWithoutContactSettingsInput = {
  create?: Prisma.XOR<Prisma.ContactCreateWithoutContactSettingsInput, Prisma.ContactUncheckedCreateWithoutContactSettingsInput>
  connectOrCreate?: Prisma.ContactCreateOrConnectWithoutContactSettingsInput
  connect?: Prisma.ContactWhereUniqueInput
}

export type ContactUpdateOneRequiredWithoutContactSettingsNestedInput = {
  create?: Prisma.XOR<Prisma.ContactCreateWithoutContactSettingsInput, Prisma.ContactUncheckedCreateWithoutContactSettingsInput>
  connectOrCreate?: Prisma.ContactCreateOrConnectWithoutContactSettingsInput
  upsert?: Prisma.ContactUpsertWithoutContactSettingsInput
  connect?: Prisma.ContactWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ContactUpdateToOneWithWhereWithoutContactSettingsInput, Prisma.ContactUpdateWithoutContactSettingsInput>, Prisma.ContactUncheckedUpdateWithoutContactSettingsInput>
}

export type ContactCreateWithoutUsersInput = {
  name: string
  recent_activity?: string | null
  status?: string | null
  avatar?: string | null
  type?: string | null
  created_at?: Date | string
  updated_at?: Date | string
  deleted_at?: Date | string | null
  messages?: Prisma.MessageCreateNestedManyWithoutContactInput
  contactRequests?: Prisma.ContactRequestCreateNestedManyWithoutContactInput
  contactSettings?: Prisma.ContactSettingsCreateNestedManyWithoutContactInput
}

export type ContactUncheckedCreateWithoutUsersInput = {
  id?: number
  name: string
  recent_activity?: string | null
  status?: string | null
  avatar?: string | null
  type?: string | null
  created_at?: Date | string
  updated_at?: Date | string
  deleted_at?: Date | string | null
  messages?: Prisma.MessageUncheckedCreateNestedManyWithoutContactInput
  contactRequests?: Prisma.ContactRequestUncheckedCreateNestedManyWithoutContactInput
  contactSettings?: Prisma.ContactSettingsUncheckedCreateNestedManyWithoutContactInput
}

export type ContactCreateOrConnectWithoutUsersInput = {
  where: Prisma.ContactWhereUniqueInput
  create: Prisma.XOR<Prisma.ContactCreateWithoutUsersInput, Prisma.ContactUncheckedCreateWithoutUsersInput>
}

export type ContactUpsertWithWhereUniqueWithoutUsersInput = {
  where: Prisma.ContactWhereUniqueInput
  update: Prisma.XOR<Prisma.ContactUpdateWithoutUsersInput, Prisma.ContactUncheckedUpdateWithoutUsersInput>
  create: Prisma.XOR<Prisma.ContactCreateWithoutUsersInput, Prisma.ContactUncheckedCreateWithoutUsersInput>
}

export type ContactUpdateWithWhereUniqueWithoutUsersInput = {
  where: Prisma.ContactWhereUniqueInput
  data: Prisma.XOR<Prisma.ContactUpdateWithoutUsersInput, Prisma.ContactUncheckedUpdateWithoutUsersInput>
}

export type ContactUpdateManyWithWhereWithoutUsersInput = {
  where: Prisma.ContactScalarWhereInput
  data: Prisma.XOR<Prisma.ContactUpdateManyMutationInput, Prisma.ContactUncheckedUpdateManyWithoutUsersInput>
}

export type ContactScalarWhereInput = {
  AND?: Prisma.ContactScalarWhereInput | Prisma.ContactScalarWhereInput[]
  OR?: Prisma.ContactScalarWhereInput[]
  NOT?: Prisma.ContactScalarWhereInput | Prisma.ContactScalarWhereInput[]
  id?: Prisma.IntFilter<"Contact"> | number
  name?: Prisma.StringFilter<"Contact"> | string
  recent_activity?: Prisma.StringNullableFilter<"Contact"> | string | null
  status?: Prisma.StringNullableFilter<"Contact"> | string | null
  avatar?: Prisma.StringNullableFilter<"Contact"> | string | null
  type?: Prisma.StringNullableFilter<"Contact"> | string | null
  created_at?: Prisma.DateTimeFilter<"Contact"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"Contact"> | Date | string
  deleted_at?: Prisma.DateTimeNullableFilter<"Contact"> | Date | string | null
}

export type ContactCreateWithoutMessagesInput = {
  name: string
  recent_activity?: string | null
  status?: string | null
  avatar?: string | null
  type?: string | null
  created_at?: Date | string
  updated_at?: Date | string
  deleted_at?: Date | string | null
  users?: Prisma.UserCreateNestedManyWithoutContactsInput
  contactRequests?: Prisma.ContactRequestCreateNestedManyWithoutContactInput
  contactSettings?: Prisma.ContactSettingsCreateNestedManyWithoutContactInput
}

export type ContactUncheckedCreateWithoutMessagesInput = {
  id?: number
  name: string
  recent_activity?: string | null
  status?: string | null
  avatar?: string | null
  type?: string | null
  created_at?: Date | string
  updated_at?: Date | string
  deleted_at?: Date | string | null
  users?: Prisma.UserUncheckedCreateNestedManyWithoutContactsInput
  contactRequests?: Prisma.ContactRequestUncheckedCreateNestedManyWithoutContactInput
  contactSettings?: Prisma.ContactSettingsUncheckedCreateNestedManyWithoutContactInput
}

export type ContactCreateOrConnectWithoutMessagesInput = {
  where: Prisma.ContactWhereUniqueInput
  create: Prisma.XOR<Prisma.ContactCreateWithoutMessagesInput, Prisma.ContactUncheckedCreateWithoutMessagesInput>
}

export type ContactUpsertWithoutMessagesInput = {
  update: Prisma.XOR<Prisma.ContactUpdateWithoutMessagesInput, Prisma.ContactUncheckedUpdateWithoutMessagesInput>
  create: Prisma.XOR<Prisma.ContactCreateWithoutMessagesInput, Prisma.ContactUncheckedCreateWithoutMessagesInput>
  where?: Prisma.ContactWhereInput
}

export type ContactUpdateToOneWithWhereWithoutMessagesInput = {
  where?: Prisma.ContactWhereInput
  data: Prisma.XOR<Prisma.ContactUpdateWithoutMessagesInput, Prisma.ContactUncheckedUpdateWithoutMessagesInput>
}

export type ContactUpdateWithoutMessagesInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  recent_activity?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  avatar?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  users?: Prisma.UserUpdateManyWithoutContactsNestedInput
  contactRequests?: Prisma.ContactRequestUpdateManyWithoutContactNestedInput
  contactSettings?: Prisma.ContactSettingsUpdateManyWithoutContactNestedInput
}

export type ContactUncheckedUpdateWithoutMessagesInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  recent_activity?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  avatar?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  users?: Prisma.UserUncheckedUpdateManyWithoutContactsNestedInput
  contactRequests?: Prisma.ContactRequestUncheckedUpdateManyWithoutContactNestedInput
  contactSettings?: Prisma.ContactSettingsUncheckedUpdateManyWithoutContactNestedInput
}

export type ContactCreateWithoutContactRequestsInput = {
  name: string
  recent_activity?: string | null
  status?: string | null
  avatar?: string | null
  type?: string | null
  created_at?: Date | string
  updated_at?: Date | string
  deleted_at?: Date | string | null
  users?: Prisma.UserCreateNestedManyWithoutContactsInput
  messages?: Prisma.MessageCreateNestedManyWithoutContactInput
  contactSettings?: Prisma.ContactSettingsCreateNestedManyWithoutContactInput
}

export type ContactUncheckedCreateWithoutContactRequestsInput = {
  id?: number
  name: string
  recent_activity?: string | null
  status?: string | null
  avatar?: string | null
  type?: string | null
  created_at?: Date | string
  updated_at?: Date | string
  deleted_at?: Date | string | null
  users?: Prisma.UserUncheckedCreateNestedManyWithoutContactsInput
  messages?: Prisma.MessageUncheckedCreateNestedManyWithoutContactInput
  contactSettings?: Prisma.ContactSettingsUncheckedCreateNestedManyWithoutContactInput
}

export type ContactCreateOrConnectWithoutContactRequestsInput = {
  where: Prisma.ContactWhereUniqueInput
  create: Prisma.XOR<Prisma.ContactCreateWithoutContactRequestsInput, Prisma.ContactUncheckedCreateWithoutContactRequestsInput>
}

export type ContactUpsertWithoutContactRequestsInput = {
  update: Prisma.XOR<Prisma.ContactUpdateWithoutContactRequestsInput, Prisma.ContactUncheckedUpdateWithoutContactRequestsInput>
  create: Prisma.XOR<Prisma.ContactCreateWithoutContactRequestsInput, Prisma.ContactUncheckedCreateWithoutContactRequestsInput>
  where?: Prisma.ContactWhereInput
}

export type ContactUpdateToOneWithWhereWithoutContactRequestsInput = {
  where?: Prisma.ContactWhereInput
  data: Prisma.XOR<Prisma.ContactUpdateWithoutContactRequestsInput, Prisma.ContactUncheckedUpdateWithoutContactRequestsInput>
}

export type ContactUpdateWithoutContactRequestsInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  recent_activity?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  avatar?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  users?: Prisma.UserUpdateManyWithoutContactsNestedInput
  messages?: Prisma.MessageUpdateManyWithoutContactNestedInput
  contactSettings?: Prisma.ContactSettingsUpdateManyWithoutContactNestedInput
}

export type ContactUncheckedUpdateWithoutContactRequestsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  recent_activity?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  avatar?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  users?: Prisma.UserUncheckedUpdateManyWithoutContactsNestedInput
  messages?: Prisma.MessageUncheckedUpdateManyWithoutContactNestedInput
  contactSettings?: Prisma.ContactSettingsUncheckedUpdateManyWithoutContactNestedInput
}

export type ContactCreateWithoutContactSettingsInput = {
  name: string
  recent_activity?: string | null
  status?: string | null
  avatar?: string | null
  type?: string | null
  created_at?: Date | string
  updated_at?: Date | string
  deleted_at?: Date | string | null
  users?: Prisma.UserCreateNestedManyWithoutContactsInput
  messages?: Prisma.MessageCreateNestedManyWithoutContactInput
  contactRequests?: Prisma.ContactRequestCreateNestedManyWithoutContactInput
}

export type ContactUncheckedCreateWithoutContactSettingsInput = {
  id?: number
  name: string
  recent_activity?: string | null
  status?: string | null
  avatar?: string | null
  type?: string | null
  created_at?: Date | string
  updated_at?: Date | string
  deleted_at?: Date | string | null
  users?: Prisma.UserUncheckedCreateNestedManyWithoutContactsInput
  messages?: Prisma.MessageUncheckedCreateNestedManyWithoutContactInput
  contactRequests?: Prisma.ContactRequestUncheckedCreateNestedManyWithoutContactInput
}

export type ContactCreateOrConnectWithoutContactSettingsInput = {
  where: Prisma.ContactWhereUniqueInput
  create: Prisma.XOR<Prisma.ContactCreateWithoutContactSettingsInput, Prisma.ContactUncheckedCreateWithoutContactSettingsInput>
}

export type ContactUpsertWithoutContactSettingsInput = {
  update: Prisma.XOR<Prisma.ContactUpdateWithoutContactSettingsInput, Prisma.ContactUncheckedUpdateWithoutContactSettingsInput>
  create: Prisma.XOR<Prisma.ContactCreateWithoutContactSettingsInput, Prisma.ContactUncheckedCreateWithoutContactSettingsInput>
  where?: Prisma.ContactWhereInput
}

export type ContactUpdateToOneWithWhereWithoutContactSettingsInput = {
  where?: Prisma.ContactWhereInput
  data: Prisma.XOR<Prisma.ContactUpdateWithoutContactSettingsInput, Prisma.ContactUncheckedUpdateWithoutContactSettingsInput>
}

export type ContactUpdateWithoutContactSettingsInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  recent_activity?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  avatar?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  users?: Prisma.UserUpdateManyWithoutContactsNestedInput
  messages?: Prisma.MessageUpdateManyWithoutContactNestedInput
  contactRequests?: Prisma.ContactRequestUpdateManyWithoutContactNestedInput
}

export type ContactUncheckedUpdateWithoutContactSettingsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  recent_activity?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  avatar?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  users?: Prisma.UserUncheckedUpdateManyWithoutContactsNestedInput
  messages?: Prisma.MessageUncheckedUpdateManyWithoutContactNestedInput
  contactRequests?: Prisma.ContactRequestUncheckedUpdateManyWithoutContactNestedInput
}

export type ContactUpdateWithoutUsersInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  recent_activity?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  avatar?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  messages?: Prisma.MessageUpdateManyWithoutContactNestedInput
  contactRequests?: Prisma.ContactRequestUpdateManyWithoutContactNestedInput
  contactSettings?: Prisma.ContactSettingsUpdateManyWithoutContactNestedInput
}

export type ContactUncheckedUpdateWithoutUsersInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  recent_activity?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  avatar?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  messages?: Prisma.MessageUncheckedUpdateManyWithoutContactNestedInput
  contactRequests?: Prisma.ContactRequestUncheckedUpdateManyWithoutContactNestedInput
  contactSettings?: Prisma.ContactSettingsUncheckedUpdateManyWithoutContactNestedInput
}

export type ContactUncheckedUpdateManyWithoutUsersInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  recent_activity?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  avatar?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}


/**
 * Count Type ContactCountOutputType
 */

export type ContactCountOutputType = {
  users: number
  messages: number
  contactRequests: number
  contactSettings: number
}

export type ContactCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  users?: boolean | ContactCountOutputTypeCountUsersArgs
  messages?: boolean | ContactCountOutputTypeCountMessagesArgs
  contactRequests?: boolean | ContactCountOutputTypeCountContactRequestsArgs
  contactSettings?: boolean | ContactCountOutputTypeCountContactSettingsArgs
}

/**
 * ContactCountOutputType without action
 */
export type ContactCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ContactCountOutputType
   */
  select?: Prisma.ContactCountOutputTypeSelect<ExtArgs> | null
}

/**
 * ContactCountOutputType without action
 */
export type ContactCountOutputTypeCountUsersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserWhereInput
}

/**
 * ContactCountOutputType without action
 */
export type ContactCountOutputTypeCountMessagesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MessageWhereInput
}

/**
 * ContactCountOutputType without action
 */
export type ContactCountOutputTypeCountContactRequestsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ContactRequestWhereInput
}

/**
 * ContactCountOutputType without action
 */
export type ContactCountOutputTypeCountContactSettingsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ContactSettingsWhereInput
}


export type ContactSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  recent_activity?: boolean
  status?: boolean
  avatar?: boolean
  type?: boolean
  created_at?: boolean
  updated_at?: boolean
  deleted_at?: boolean
  users?: boolean | Prisma.Contact$usersArgs<ExtArgs>
  messages?: boolean | Prisma.Contact$messagesArgs<ExtArgs>
  contactRequests?: boolean | Prisma.Contact$contactRequestsArgs<ExtArgs>
  contactSettings?: boolean | Prisma.Contact$contactSettingsArgs<ExtArgs>
  _count?: boolean | Prisma.ContactCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["contact"]>

export type ContactSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  recent_activity?: boolean
  status?: boolean
  avatar?: boolean
  type?: boolean
  created_at?: boolean
  updated_at?: boolean
  deleted_at?: boolean
}, ExtArgs["result"]["contact"]>

export type ContactSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  recent_activity?: boolean
  status?: boolean
  avatar?: boolean
  type?: boolean
  created_at?: boolean
  updated_at?: boolean
  deleted_at?: boolean
}, ExtArgs["result"]["contact"]>

export type ContactSelectScalar = {
  id?: boolean
  name?: boolean
  recent_activity?: boolean
  status?: boolean
  avatar?: boolean
  type?: boolean
  created_at?: boolean
  updated_at?: boolean
  deleted_at?: boolean
}

export type ContactOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "recent_activity" | "status" | "avatar" | "type" | "created_at" | "updated_at" | "deleted_at", ExtArgs["result"]["contact"]>
export type ContactInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  users?: boolean | Prisma.Contact$usersArgs<ExtArgs>
  messages?: boolean | Prisma.Contact$messagesArgs<ExtArgs>
  contactRequests?: boolean | Prisma.Contact$contactRequestsArgs<ExtArgs>
  contactSettings?: boolean | Prisma.Contact$contactSettingsArgs<ExtArgs>
  _count?: boolean | Prisma.ContactCountOutputTypeDefaultArgs<ExtArgs>
}
export type ContactIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type ContactIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $ContactPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Contact"
  objects: {
    users: Prisma.$UserPayload<ExtArgs>[]
    messages: Prisma.$MessagePayload<ExtArgs>[]
    contactRequests: Prisma.$ContactRequestPayload<ExtArgs>[]
    contactSettings: Prisma.$ContactSettingsPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    name: string
    recent_activity: string | null
    status: string | null
    avatar: string | null
    type: string | null
    created_at: Date
    updated_at: Date
    deleted_at: Date | null
  }, ExtArgs["result"]["contact"]>
  composites: {}
}

export type ContactGetPayload<S extends boolean | null | undefined | ContactDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ContactPayload, S>

export type ContactCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ContactFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ContactCountAggregateInputType | true
  }

export interface ContactDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Contact'], meta: { name: 'Contact' } }
  /**
   * Find zero or one Contact that matches the filter.
   * @param {ContactFindUniqueArgs} args - Arguments to find a Contact
   * @example
   * // Get one Contact
   * const contact = await prisma.contact.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ContactFindUniqueArgs>(args: Prisma.SelectSubset<T, ContactFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ContactClient<runtime.Types.Result.GetResult<Prisma.$ContactPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Contact that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ContactFindUniqueOrThrowArgs} args - Arguments to find a Contact
   * @example
   * // Get one Contact
   * const contact = await prisma.contact.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ContactFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ContactFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ContactClient<runtime.Types.Result.GetResult<Prisma.$ContactPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Contact that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ContactFindFirstArgs} args - Arguments to find a Contact
   * @example
   * // Get one Contact
   * const contact = await prisma.contact.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ContactFindFirstArgs>(args?: Prisma.SelectSubset<T, ContactFindFirstArgs<ExtArgs>>): Prisma.Prisma__ContactClient<runtime.Types.Result.GetResult<Prisma.$ContactPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Contact that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ContactFindFirstOrThrowArgs} args - Arguments to find a Contact
   * @example
   * // Get one Contact
   * const contact = await prisma.contact.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ContactFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ContactFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ContactClient<runtime.Types.Result.GetResult<Prisma.$ContactPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Contacts that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ContactFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Contacts
   * const contacts = await prisma.contact.findMany()
   * 
   * // Get first 10 Contacts
   * const contacts = await prisma.contact.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const contactWithIdOnly = await prisma.contact.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ContactFindManyArgs>(args?: Prisma.SelectSubset<T, ContactFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ContactPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Contact.
   * @param {ContactCreateArgs} args - Arguments to create a Contact.
   * @example
   * // Create one Contact
   * const Contact = await prisma.contact.create({
   *   data: {
   *     // ... data to create a Contact
   *   }
   * })
   * 
   */
  create<T extends ContactCreateArgs>(args: Prisma.SelectSubset<T, ContactCreateArgs<ExtArgs>>): Prisma.Prisma__ContactClient<runtime.Types.Result.GetResult<Prisma.$ContactPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Contacts.
   * @param {ContactCreateManyArgs} args - Arguments to create many Contacts.
   * @example
   * // Create many Contacts
   * const contact = await prisma.contact.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ContactCreateManyArgs>(args?: Prisma.SelectSubset<T, ContactCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Contacts and returns the data saved in the database.
   * @param {ContactCreateManyAndReturnArgs} args - Arguments to create many Contacts.
   * @example
   * // Create many Contacts
   * const contact = await prisma.contact.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Contacts and only return the `id`
   * const contactWithIdOnly = await prisma.contact.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ContactCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ContactCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ContactPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Contact.
   * @param {ContactDeleteArgs} args - Arguments to delete one Contact.
   * @example
   * // Delete one Contact
   * const Contact = await prisma.contact.delete({
   *   where: {
   *     // ... filter to delete one Contact
   *   }
   * })
   * 
   */
  delete<T extends ContactDeleteArgs>(args: Prisma.SelectSubset<T, ContactDeleteArgs<ExtArgs>>): Prisma.Prisma__ContactClient<runtime.Types.Result.GetResult<Prisma.$ContactPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Contact.
   * @param {ContactUpdateArgs} args - Arguments to update one Contact.
   * @example
   * // Update one Contact
   * const contact = await prisma.contact.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ContactUpdateArgs>(args: Prisma.SelectSubset<T, ContactUpdateArgs<ExtArgs>>): Prisma.Prisma__ContactClient<runtime.Types.Result.GetResult<Prisma.$ContactPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Contacts.
   * @param {ContactDeleteManyArgs} args - Arguments to filter Contacts to delete.
   * @example
   * // Delete a few Contacts
   * const { count } = await prisma.contact.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ContactDeleteManyArgs>(args?: Prisma.SelectSubset<T, ContactDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Contacts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ContactUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Contacts
   * const contact = await prisma.contact.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ContactUpdateManyArgs>(args: Prisma.SelectSubset<T, ContactUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Contacts and returns the data updated in the database.
   * @param {ContactUpdateManyAndReturnArgs} args - Arguments to update many Contacts.
   * @example
   * // Update many Contacts
   * const contact = await prisma.contact.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Contacts and only return the `id`
   * const contactWithIdOnly = await prisma.contact.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ContactUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ContactUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ContactPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Contact.
   * @param {ContactUpsertArgs} args - Arguments to update or create a Contact.
   * @example
   * // Update or create a Contact
   * const contact = await prisma.contact.upsert({
   *   create: {
   *     // ... data to create a Contact
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Contact we want to update
   *   }
   * })
   */
  upsert<T extends ContactUpsertArgs>(args: Prisma.SelectSubset<T, ContactUpsertArgs<ExtArgs>>): Prisma.Prisma__ContactClient<runtime.Types.Result.GetResult<Prisma.$ContactPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Contacts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ContactCountArgs} args - Arguments to filter Contacts to count.
   * @example
   * // Count the number of Contacts
   * const count = await prisma.contact.count({
   *   where: {
   *     // ... the filter for the Contacts we want to count
   *   }
   * })
  **/
  count<T extends ContactCountArgs>(
    args?: Prisma.Subset<T, ContactCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ContactCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Contact.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ContactAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ContactAggregateArgs>(args: Prisma.Subset<T, ContactAggregateArgs>): Prisma.PrismaPromise<GetContactAggregateType<T>>

  /**
   * Group by Contact.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ContactGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ContactGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ContactGroupByArgs['orderBy'] }
      : { orderBy?: ContactGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ContactGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetContactGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Contact model
 */
readonly fields: ContactFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Contact.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ContactClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  users<T extends Prisma.Contact$usersArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Contact$usersArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  messages<T extends Prisma.Contact$messagesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Contact$messagesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MessagePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  contactRequests<T extends Prisma.Contact$contactRequestsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Contact$contactRequestsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ContactRequestPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  contactSettings<T extends Prisma.Contact$contactSettingsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Contact$contactSettingsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ContactSettingsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Contact model
 */
export interface ContactFieldRefs {
  readonly id: Prisma.FieldRef<"Contact", 'Int'>
  readonly name: Prisma.FieldRef<"Contact", 'String'>
  readonly recent_activity: Prisma.FieldRef<"Contact", 'String'>
  readonly status: Prisma.FieldRef<"Contact", 'String'>
  readonly avatar: Prisma.FieldRef<"Contact", 'String'>
  readonly type: Prisma.FieldRef<"Contact", 'String'>
  readonly created_at: Prisma.FieldRef<"Contact", 'DateTime'>
  readonly updated_at: Prisma.FieldRef<"Contact", 'DateTime'>
  readonly deleted_at: Prisma.FieldRef<"Contact", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Contact findUnique
 */
export type ContactFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Contact
   */
  select?: Prisma.ContactSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Contact
   */
  omit?: Prisma.ContactOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContactInclude<ExtArgs> | null
  /**
   * Filter, which Contact to fetch.
   */
  where: Prisma.ContactWhereUniqueInput
}

/**
 * Contact findUniqueOrThrow
 */
export type ContactFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Contact
   */
  select?: Prisma.ContactSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Contact
   */
  omit?: Prisma.ContactOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContactInclude<ExtArgs> | null
  /**
   * Filter, which Contact to fetch.
   */
  where: Prisma.ContactWhereUniqueInput
}

/**
 * Contact findFirst
 */
export type ContactFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Contact
   */
  select?: Prisma.ContactSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Contact
   */
  omit?: Prisma.ContactOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContactInclude<ExtArgs> | null
  /**
   * Filter, which Contact to fetch.
   */
  where?: Prisma.ContactWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Contacts to fetch.
   */
  orderBy?: Prisma.ContactOrderByWithRelationInput | Prisma.ContactOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Contacts.
   */
  cursor?: Prisma.ContactWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Contacts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Contacts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Contacts.
   */
  distinct?: Prisma.ContactScalarFieldEnum | Prisma.ContactScalarFieldEnum[]
}

/**
 * Contact findFirstOrThrow
 */
export type ContactFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Contact
   */
  select?: Prisma.ContactSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Contact
   */
  omit?: Prisma.ContactOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContactInclude<ExtArgs> | null
  /**
   * Filter, which Contact to fetch.
   */
  where?: Prisma.ContactWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Contacts to fetch.
   */
  orderBy?: Prisma.ContactOrderByWithRelationInput | Prisma.ContactOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Contacts.
   */
  cursor?: Prisma.ContactWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Contacts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Contacts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Contacts.
   */
  distinct?: Prisma.ContactScalarFieldEnum | Prisma.ContactScalarFieldEnum[]
}

/**
 * Contact findMany
 */
export type ContactFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Contact
   */
  select?: Prisma.ContactSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Contact
   */
  omit?: Prisma.ContactOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContactInclude<ExtArgs> | null
  /**
   * Filter, which Contacts to fetch.
   */
  where?: Prisma.ContactWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Contacts to fetch.
   */
  orderBy?: Prisma.ContactOrderByWithRelationInput | Prisma.ContactOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Contacts.
   */
  cursor?: Prisma.ContactWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Contacts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Contacts.
   */
  skip?: number
  distinct?: Prisma.ContactScalarFieldEnum | Prisma.ContactScalarFieldEnum[]
}

/**
 * Contact create
 */
export type ContactCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Contact
   */
  select?: Prisma.ContactSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Contact
   */
  omit?: Prisma.ContactOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContactInclude<ExtArgs> | null
  /**
   * The data needed to create a Contact.
   */
  data: Prisma.XOR<Prisma.ContactCreateInput, Prisma.ContactUncheckedCreateInput>
}

/**
 * Contact createMany
 */
export type ContactCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Contacts.
   */
  data: Prisma.ContactCreateManyInput | Prisma.ContactCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Contact createManyAndReturn
 */
export type ContactCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Contact
   */
  select?: Prisma.ContactSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Contact
   */
  omit?: Prisma.ContactOmit<ExtArgs> | null
  /**
   * The data used to create many Contacts.
   */
  data: Prisma.ContactCreateManyInput | Prisma.ContactCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Contact update
 */
export type ContactUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Contact
   */
  select?: Prisma.ContactSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Contact
   */
  omit?: Prisma.ContactOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContactInclude<ExtArgs> | null
  /**
   * The data needed to update a Contact.
   */
  data: Prisma.XOR<Prisma.ContactUpdateInput, Prisma.ContactUncheckedUpdateInput>
  /**
   * Choose, which Contact to update.
   */
  where: Prisma.ContactWhereUniqueInput
}

/**
 * Contact updateMany
 */
export type ContactUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Contacts.
   */
  data: Prisma.XOR<Prisma.ContactUpdateManyMutationInput, Prisma.ContactUncheckedUpdateManyInput>
  /**
   * Filter which Contacts to update
   */
  where?: Prisma.ContactWhereInput
  /**
   * Limit how many Contacts to update.
   */
  limit?: number
}

/**
 * Contact updateManyAndReturn
 */
export type ContactUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Contact
   */
  select?: Prisma.ContactSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Contact
   */
  omit?: Prisma.ContactOmit<ExtArgs> | null
  /**
   * The data used to update Contacts.
   */
  data: Prisma.XOR<Prisma.ContactUpdateManyMutationInput, Prisma.ContactUncheckedUpdateManyInput>
  /**
   * Filter which Contacts to update
   */
  where?: Prisma.ContactWhereInput
  /**
   * Limit how many Contacts to update.
   */
  limit?: number
}

/**
 * Contact upsert
 */
export type ContactUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Contact
   */
  select?: Prisma.ContactSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Contact
   */
  omit?: Prisma.ContactOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContactInclude<ExtArgs> | null
  /**
   * The filter to search for the Contact to update in case it exists.
   */
  where: Prisma.ContactWhereUniqueInput
  /**
   * In case the Contact found by the `where` argument doesn't exist, create a new Contact with this data.
   */
  create: Prisma.XOR<Prisma.ContactCreateInput, Prisma.ContactUncheckedCreateInput>
  /**
   * In case the Contact was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ContactUpdateInput, Prisma.ContactUncheckedUpdateInput>
}

/**
 * Contact delete
 */
export type ContactDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Contact
   */
  select?: Prisma.ContactSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Contact
   */
  omit?: Prisma.ContactOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContactInclude<ExtArgs> | null
  /**
   * Filter which Contact to delete.
   */
  where: Prisma.ContactWhereUniqueInput
}

/**
 * Contact deleteMany
 */
export type ContactDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Contacts to delete
   */
  where?: Prisma.ContactWhereInput
  /**
   * Limit how many Contacts to delete.
   */
  limit?: number
}

/**
 * Contact.users
 */
export type Contact$usersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  where?: Prisma.UserWhereInput
  orderBy?: Prisma.UserOrderByWithRelationInput | Prisma.UserOrderByWithRelationInput[]
  cursor?: Prisma.UserWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.UserScalarFieldEnum | Prisma.UserScalarFieldEnum[]
}

/**
 * Contact.messages
 */
export type Contact$messagesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Message
   */
  select?: Prisma.MessageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Message
   */
  omit?: Prisma.MessageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MessageInclude<ExtArgs> | null
  where?: Prisma.MessageWhereInput
  orderBy?: Prisma.MessageOrderByWithRelationInput | Prisma.MessageOrderByWithRelationInput[]
  cursor?: Prisma.MessageWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.MessageScalarFieldEnum | Prisma.MessageScalarFieldEnum[]
}

/**
 * Contact.contactRequests
 */
export type Contact$contactRequestsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ContactRequest
   */
  select?: Prisma.ContactRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ContactRequest
   */
  omit?: Prisma.ContactRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContactRequestInclude<ExtArgs> | null
  where?: Prisma.ContactRequestWhereInput
  orderBy?: Prisma.ContactRequestOrderByWithRelationInput | Prisma.ContactRequestOrderByWithRelationInput[]
  cursor?: Prisma.ContactRequestWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ContactRequestScalarFieldEnum | Prisma.ContactRequestScalarFieldEnum[]
}

/**
 * Contact.contactSettings
 */
export type Contact$contactSettingsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ContactSettings
   */
  select?: Prisma.ContactSettingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ContactSettings
   */
  omit?: Prisma.ContactSettingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContactSettingsInclude<ExtArgs> | null
  where?: Prisma.ContactSettingsWhereInput
  orderBy?: Prisma.ContactSettingsOrderByWithRelationInput | Prisma.ContactSettingsOrderByWithRelationInput[]
  cursor?: Prisma.ContactSettingsWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ContactSettingsScalarFieldEnum | Prisma.ContactSettingsScalarFieldEnum[]
}

/**
 * Contact without action
 */
export type ContactDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Contact
   */
  select?: Prisma.ContactSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Contact
   */
  omit?: Prisma.ContactOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContactInclude<ExtArgs> | null
}
