
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models.js'
export type * from './prismaNamespace.js'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  User: 'User',
  Branch: 'Branch',
  Role: 'Role',
  Permission: 'Permission',
  Theme: 'Theme',
  Message: 'Message',
  Contact: 'Contact',
  ContactRequest: 'ContactRequest',
  ContactSettings: 'ContactSettings'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UserScalarFieldEnum = {
  id: 'id',
  first_name: 'first_name',
  middle_name: 'middle_name',
  last_name: 'last_name',
  email: 'email',
  password: 'password',
  created_at: 'created_at',
  updated_at: 'updated_at',
  deleted_at: 'deleted_at'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const BranchScalarFieldEnum = {
  id: 'id',
  name: 'name',
  status: 'status',
  created_at: 'created_at',
  updated_at: 'updated_at',
  deleted_at: 'deleted_at'
} as const

export type BranchScalarFieldEnum = (typeof BranchScalarFieldEnum)[keyof typeof BranchScalarFieldEnum]


export const RoleScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  created_at: 'created_at',
  updated_at: 'updated_at',
  deleted_at: 'deleted_at'
} as const

export type RoleScalarFieldEnum = (typeof RoleScalarFieldEnum)[keyof typeof RoleScalarFieldEnum]


export const PermissionScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  created_at: 'created_at',
  updated_at: 'updated_at',
  deleted_at: 'deleted_at'
} as const

export type PermissionScalarFieldEnum = (typeof PermissionScalarFieldEnum)[keyof typeof PermissionScalarFieldEnum]


export const ThemeScalarFieldEnum = {
  id: 'id',
  name: 'name',
  contrast: 'contrast',
  border_radius: 'border_radius',
  dark_mode: 'dark_mode',
  primary: 'primary',
  secondary: 'secondary',
  neutral: 'neutral',
  success: 'success',
  error: 'error',
  info: 'info',
  tertiary: 'tertiary',
  warning: 'warning',
  created_at: 'created_at',
  updated_at: 'updated_at',
  deleted_at: 'deleted_at'
} as const

export type ThemeScalarFieldEnum = (typeof ThemeScalarFieldEnum)[keyof typeof ThemeScalarFieldEnum]


export const MessageScalarFieldEnum = {
  id: 'id',
  message: 'message',
  type: 'type',
  created_at: 'created_at',
  updated_at: 'updated_at',
  deleted_at: 'deleted_at',
  userId: 'userId',
  contactId: 'contactId',
  reply_to_id: 'reply_to_id'
} as const

export type MessageScalarFieldEnum = (typeof MessageScalarFieldEnum)[keyof typeof MessageScalarFieldEnum]


export const ContactScalarFieldEnum = {
  id: 'id',
  name: 'name',
  recent_activity: 'recent_activity',
  status: 'status',
  avatar: 'avatar',
  type: 'type',
  created_at: 'created_at',
  updated_at: 'updated_at',
  deleted_at: 'deleted_at'
} as const

export type ContactScalarFieldEnum = (typeof ContactScalarFieldEnum)[keyof typeof ContactScalarFieldEnum]


export const ContactRequestScalarFieldEnum = {
  id: 'id',
  status: 'status',
  created_at: 'created_at',
  updated_at: 'updated_at',
  deleted_at: 'deleted_at',
  userId: 'userId',
  contactId: 'contactId'
} as const

export type ContactRequestScalarFieldEnum = (typeof ContactRequestScalarFieldEnum)[keyof typeof ContactRequestScalarFieldEnum]


export const ContactSettingsScalarFieldEnum = {
  id: 'id',
  name: 'name',
  recent_activity: 'recent_activity',
  marked_as_read: 'marked_as_read',
  muted: 'muted',
  ignored: 'ignored',
  archived: 'archived',
  pinned: 'pinned',
  created_at: 'created_at',
  updated_at: 'updated_at',
  deleted_at: 'deleted_at',
  userId: 'userId',
  contactId: 'contactId'
} as const

export type ContactSettingsScalarFieldEnum = (typeof ContactSettingsScalarFieldEnum)[keyof typeof ContactSettingsScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const UserOrderByRelevanceFieldEnum = {
  first_name: 'first_name',
  middle_name: 'middle_name',
  last_name: 'last_name',
  email: 'email',
  password: 'password'
} as const

export type UserOrderByRelevanceFieldEnum = (typeof UserOrderByRelevanceFieldEnum)[keyof typeof UserOrderByRelevanceFieldEnum]


export const BranchOrderByRelevanceFieldEnum = {
  name: 'name',
  status: 'status'
} as const

export type BranchOrderByRelevanceFieldEnum = (typeof BranchOrderByRelevanceFieldEnum)[keyof typeof BranchOrderByRelevanceFieldEnum]


export const RoleOrderByRelevanceFieldEnum = {
  name: 'name',
  description: 'description'
} as const

export type RoleOrderByRelevanceFieldEnum = (typeof RoleOrderByRelevanceFieldEnum)[keyof typeof RoleOrderByRelevanceFieldEnum]


export const PermissionOrderByRelevanceFieldEnum = {
  name: 'name',
  description: 'description'
} as const

export type PermissionOrderByRelevanceFieldEnum = (typeof PermissionOrderByRelevanceFieldEnum)[keyof typeof PermissionOrderByRelevanceFieldEnum]


export const ThemeOrderByRelevanceFieldEnum = {
  name: 'name',
  border_radius: 'border_radius',
  primary: 'primary',
  secondary: 'secondary',
  neutral: 'neutral',
  success: 'success',
  error: 'error',
  info: 'info',
  tertiary: 'tertiary',
  warning: 'warning'
} as const

export type ThemeOrderByRelevanceFieldEnum = (typeof ThemeOrderByRelevanceFieldEnum)[keyof typeof ThemeOrderByRelevanceFieldEnum]


export const MessageOrderByRelevanceFieldEnum = {
  message: 'message',
  type: 'type'
} as const

export type MessageOrderByRelevanceFieldEnum = (typeof MessageOrderByRelevanceFieldEnum)[keyof typeof MessageOrderByRelevanceFieldEnum]


export const ContactOrderByRelevanceFieldEnum = {
  name: 'name',
  recent_activity: 'recent_activity',
  status: 'status',
  avatar: 'avatar',
  type: 'type'
} as const

export type ContactOrderByRelevanceFieldEnum = (typeof ContactOrderByRelevanceFieldEnum)[keyof typeof ContactOrderByRelevanceFieldEnum]


export const ContactRequestOrderByRelevanceFieldEnum = {
  status: 'status'
} as const

export type ContactRequestOrderByRelevanceFieldEnum = (typeof ContactRequestOrderByRelevanceFieldEnum)[keyof typeof ContactRequestOrderByRelevanceFieldEnum]


export const ContactSettingsOrderByRelevanceFieldEnum = {
  name: 'name',
  recent_activity: 'recent_activity'
} as const

export type ContactSettingsOrderByRelevanceFieldEnum = (typeof ContactSettingsOrderByRelevanceFieldEnum)[keyof typeof ContactSettingsOrderByRelevanceFieldEnum]

